src/swapnilMaheshwari/BankOperations.java, src/swapnilMaheshwari/CalculatorFunction.java, src/swapnilMaheshwari/Example1.java, src/swapnilMaheshwari/Example2.java, src/swapnilMaheshwari/Example3.java
=> Assignment 1-5_Swapnil

src/hindaviIngle/BankDetails.java, src/hindaviIngle/Calculator.java, src/hindaviIngle/PrimeExample5.java, src/hindaviIngle/Result.java, src/hindaviIngle/StudentInfo.java
=> Hindavi assigments

src/shubhamG/Bank.java, src/shubhamG/Calculator.java, src/shubhamG/DaysIndex.java, src/shubhamG/StudentInfo.java
=> Assignment_1_5_ShubhamG

src/deepakBorse/BankDetails.java, src/deepakBorse/CalculatorPara.java, src/deepakBorse/Calender.java, src/deepakBorse/FirstProg.java, src/deepakBorse/PrimeNumber.java, src/deepakBorse/StudentInfo.java, src/deepakBorse/StudentResult.java, src/deepakBorse/loopAssignment.java
=> Deepak borse assignments

src/shivaniGour/Bank.java, src/shivaniGour/Calculator.java, src/shivaniGour/CalculatorParam.java, src/shivaniGour/Calendar.java, src/shivaniGour/FirstProg.java, src/shivaniGour/MathOperations.java, src/shivaniGour/PrimeNumber.java, src/shivaniGour/StudentInfo.java
=> Assignments are added

src/komalShrivastava/BankBalance.java, src/komalShrivastava/Calculator.java, src/komalShrivastava/CalculatorParams.java, src/komalShrivastava/DayWeekMonthIndex.java, src/komalShrivastava/ExamResult.java, src/komalShrivastava/NumberGames.java, src/komalShrivastava/PrimeNumber.java, src/komalShrivastava/Student.java, src/komalShrivastava/StudentDetails.java, src/komalShrivastava/StudentInfo.java
Added previous assignments from Day 1 till Day 8.
=> KomalShrivastava_Assignments_28thAug2022

src/akankshaSharma/Example1.java, src/monikaDwivedi/PrimeNumber.java, src/nikeshM/bank.java, src/technocredits/BankDetail.java, src/technocredits/DefaultDataType.java, src/technocredits/Example6.java, src/technocredits/Example7.java, src/technocredits/Example8.java, src/technocredits/Example9.java
=> Assignment6_9_Krishna

src/shubhamG/LoopPractice.java, src/shubhamG/PrimeNumber.java, src/shubhamG/Results.java
=> Assignment_6_9_ShubhamG

src/hindaviIngle/Example1.java, src/hindaviIngle/Example2.java, src/hindaviIngle/Numbers.java, src/hindaviIngle/PrimeExample1.java, src/hindaviIngle/Student.java
=> Assignment6_9

src/shivaniGour/Example.java
=> New file Example.java has been added

src/harshalRane/PrimeNumber.java, src/harshalRane/StudentDetails.java, src/harshalRane/StudentInfo.java, src/harshalRane/StudentResult.java
=> Assignment6_9_Harshal

src/pujaSah/BankDetails.java, src/pujaSah/StaticExample1.java, src/pujaSah/StaticExample2.java, src/pujaSah/StaticExample3.java, src/pujaSah/StaticExample4.java
Program 1:
Program : 2
Program : 3
=> Assignment6_10_Puja

src/shivaniLikhia/PrimeNumbers.java, src/shivaniLikhia/StaticExample.java, src/shivaniLikhia/StudentInfo.java, src/shivaniLikhia/Weekday.java
=> Assignment6_9_ShivaniL

src/swapnilMaheshwari/Example4.java, src/swapnilMaheshwari/ForProgramms.java, src/swapnilMaheshwari/ParamEx1.java, src/swapnilMaheshwari/PrimeNumber.java
=> Assignment 6_9_SwapnilAssignment

src/asthaSrivastava/Example4.java, src/asthaSrivastava/FaceB.java
=> Assignments_Astha_6_9

src/manjiri/ExamResult.java, src/manjiri/PrimeNumber.java
=> Assignment6_9_Manjiri

src/chaitanyaMankar/Calculator.java
=> Assignment7

src/nikitaPhase/Example4.java, src/nikitaPhase/LoopEx2.java, src/nikitaPhase/PrimeNumberEx1.java, src/nikitaPhase/ScoreResult.java
=> Assignment6_9_Nikita_Phase

src/deepakPatil/GitPractice.java
=> Git Practice file

src/gauravSahu/Account.java, src/gauravSahu/Calci.java, src/gauravSahu/Employee.java, src/gauravSahu/Exam.java, src/gauravSahu/School.java
=> Assignment_9

src/pallaviRaut/Bank.java, src/pallaviRaut/Calculator.java, src/pallaviRaut/Calculatorparam.java, src/pallaviRaut/Calendar.java, src/pallaviRaut/LoopExample1.java, src/pallaviRaut/PrimeNumber.java, src/pallaviRaut/StaticExample1.java, src/pallaviRaut/StudentGradeInfo.java, src/pallaviRaut/StudentInfo.java
PrimeNum
Bank
calculatorparam
forloop
=> Assignments #1-9 Program files added

src/ankitaBarwad/PrimeNumber.java, src/ankitaBarwad/Result.java, src/ankitaBarwad/Student.java, src/ankitaBarwad/StudentInfo.java
=> Assignment6_9_Ankita

src/akankshaSharma/FindPrime.java, src/akankshaSharma/Result.java, src/akankshaSharma/StudentInfo.java
=> Assignments_6_9

src/monali/BankDetails.java, src/monali/Dates.java, src/monali/LoopInfo.java, src/monali/StudentInfo.java, src/monali/Year.java
=> Assignment6_9_Monali

src/amolMule/Calculator.java, src/amolMule/Calculator1.java, src/amolMule/DivByFiveAndThree.java, src/amolMule/EvenNumbers.java, src/amolMule/Math.java, src/amolMule/ReverseOrders.java, src/amolMule/Student.java
=> Assignement6_9_Amol

src/pranjaliV/Calender.java, src/pranjaliV/Example.java, src/pranjaliV/LoopEx5.java, src/pranjaliV/PrimeNumber.java, src/pranjaliV/Result.java, src/pranjaliV/StudentInfo.java
=> Pranjali_Assignment_6-9

src/swatiM/Calculator.java, src/swatiM/Calender.java, src/swatiM/ForLoopExp.java, src/swatiM/PrimeNumber.java, src/swatiM/calculatorNew.java
=> adding Assignments 6 to 9

src/technocredits/Assignment_10_IfElse.java
=> Assignment_10_Krishna

src/apurvaBabel/ForLoop.java, src/apurvaBabel/MonthIndex.java, src/apurvaBabel/PrimeNumber.java, src/apurvaBabel/Result.java, src/apurvaBabel/StudentInfo.java
=> Assignment6_9_ApurvaB

src/deepakBorse/Example4.java
=> Example4 added

src/pujaSah/CountNumbers.java, src/pujaSah/NumberDivisibility.java, src/pujaSah/PrimeNumber.java, src/pujaSah/PrimeNumber2.java, src/pujaSah/StudentTestResult.java
Program1:
Program2:
Program3:
Program4:
Program5:
=> Assignment6_to_10_Updated

src/gauravSahu/Sector4.java
=> Assignment_Sample

src/adittyThakare/Assignment10.java
Programming Test - 1 : 28th Aug'2022
=> Assignment10_Aditty

src/shubhamG/Test1.java
=> ShubhamG_Test1

src/shivaniGour/Test1_ForLoop.java
=> Added Test1 ForLoop

src/ankitaBarwad/Test1_ForLoop.java
=> Test1_AnkitaB

src/harshalRane/PrintNum.java
=> Test1_Harshal

src/komalShrivastava/Test1.java
=> Test1_KomalShrivastava~5mins

src/manjiri/ProgrammingTest1_loop.java
=> Test1_Manjiri

src/anujaD/Testloop.java
=> Anuja_Test1

src/maheshSantoki/ForLoopEx2.java
Assignment 10: Mahesh Santoki:
=> Assignment_10_MaheshS

src/mohiniA/TestDivide.java
=> Test1_Mohini

src/titikshaG/Bank.java, src/titikshaG/BankDet.java, src/titikshaG/BankDetails.java, src/titikshaG/Cal.java, src/titikshaG/Mod.java, src/titikshaG/Modulation.java, src/titikshaG/calculator.java
=> Test1 titiksha

src/anujaD/LoopEx7.java, src/anujaD/Practiceprog.java, src/anujaD/Test.java, src/anujaD/WhileLoopEx1.java
=> Test1 anuja

src/akankshaVyas/DivisibleBy3n7.java
=> Test1.AkankshaVyas

src/asthaSrivastava/PrintNumber.java
=> Test1_Astha

src/shivaniLikhia/First3NumDivBy3and7.java
=> Test1_ShivaniL

src/pujaSah/NumberDivisibilityBy3And7.java
=> Test1_PujaSah_28Aug2022

src/shraddhaRekhate/LoopEx6.java
=> Test1_Shraddha

src/chaitanyaMankar/FirstThree.java
=> Test1 chaitanya

src/smitaVetal/Divisible.java
=> Test1_Smita

src/apurvaBabel/Test1.java
=> Test1_ApurvaB

src/swatiM/Test1.java
=> Test1_Swati

src/pallaviRaut/DivisibleBy3and7.java
=> Test1_Pallavi

src/hindaviIngle/NoisDivisible3and7.java
=> Test1_Hindavi

src/deepakBorse/ProgrammingTest1.java
=> ProgrammingTest1 DeepakB

src/kiran/Print.java
=> Assignment_6_8_kiran

src/pranjaliV/Test1Pranjali.java
=> Test1_Pranjali_V

src/amolMule/Divisible.java
Test 1: First 3 numbers divisible by 3 and 7
=> Test1_Amol

src/swapnilMaheshwari/DivisableBy3and7.java
=> Assignment 10

src/vibhaS/LoopEx1.java
=> Test1_Vibha

src/saroj/DivisibileBy3And7.java
=> Test1_Saroj_DivisibleBy3And7

src/nehaniG/BankOperations.java, src/nehaniG/Calculator.java, src/nehaniG/Calculator1.java, src/nehaniG/Calender.java, src/nehaniG/Days.java, src/nehaniG/Example4.java, src/nehaniG/LoopExample.java, src/nehaniG/PrimeNumber.java, src/nehaniG/WeekDays.java
removed git.ignore file.
please review.
=> Assignment_10_Nehanig

src/gauravSahu/Divisible.java, src/gauravSahu/LoopEx6.java
Assignment- Programming Test - 1 : 28th Aug'2022
On User defined range, print first 3 numbers which are divible by 3 and 7.
input : 20 to 100
output : 21
42
63
Note : Use for loop
=> Assignment_Test_1_Gaurav

src/sagarY/DivisibleBy3And7.java, src/sagarY/PrimeList.java, src/sagarY/WhileLoop.java
=> Test1_SagarY

src/nikeshM/Division.java
=> Test1_Nikesh

src/amrutaSagne/CheckNumbers.java
=> Test1_Amruta

src/vinod/Divisibleby3and7.java
=> Programe for divisible

src/rahulSaswadkar/DivisibleBy3And7.java
=> Test1_Rahul

src/pankajBhatt/ProgrammingTest1.java
Assignment- Programming Test - 1 : 28th Aug'2022
On User defined range, print first 3 numbers which are divisible by 3 and 7.
input : 20 to 100
output : 21
42
63
=> ProgrammingTest1.java

src/jagruti/Assignment_Jagruti28Aug.java
=> Jagruti_Assignment28Aug

src/narendraD/DivisibleByNumbers.java
Assignment_DivisibleByNumbers:
=> Test1 narendra

src/monikaDwivedi/Assignment_28_aug.java, src/monikaDwivedi/LoopEx7.java
=> MonikaD28AugAssignment

src/deepakPatil/ProgramTest1.java
=> Program Test1

src/ojaswini/Calculator.java, src/ojaswini/CalculatorProgram.java
=> Assignment 1 ojaswini

src/ojaswini/Bank.java
=> Assignment_2_ojaswini

src/ojaswini/CalculatorParameterised.java
=> Assignment_3_ojaswini

src/sanket/ForLoopExample.java, src/sanket/PrimeNumber.java, src/sanket/StudentInfo.java, src/sanket/StudentResult.java
=> Assignment6_9_Sanket

src/niveditaGavade/LoopTest.java, src/niveditaGavade/StudentInfo.java
=> Test1_Nivedita

src/madanPatil/Assignment10.java, src/madanPatil/PrimeNumber.java
=> Assignment_10_Madan

src/hardikBhatia/ProgramTest1.java
On User defined range, print first 3 numbers which are divisible by 3 and 7.
=> User defined range, print first 3 numbers which are divisible by 3 and 7

src/nikitaPhase/Assignment_28_aug.java
=> Assignment_10_NikitaP

src/hemanshi/Assignment10.java
=> Test1_Hemanshi

src/vibhaS/Days.java, src/vibhaS/Example1.java, src/vibhaS/Example2.java, src/vibhaS/StudentInfo.java, src/vibhaS/StudentResult.java
Assignment1_5_vibhaS please review
=> Assignment1_5_vibha

src/harshalRane/PrintLastThreeNumbers.java
Assignment10_30thAugust_Print_Last_3_NumbersDivisible by 3 and 7
=> Assignment10_30thAugust_Print_LAst_3_Numbers

src/adittyThakare/Assignment10_Last3Numbers.java
Find last 3 numbers divisible by 3 and 7 output:
=> Assignment10_Aditty_30Aug

src/rohanNaik/TestModification.java
=> Today's Assignments(30th Aug). Both versions in single class

src/abhijeet/ProgramTest1.java
=> Test1_AbhijeetM

src/pujaSah/InitialAssignmentBankDetail.java, src/pujaSah/InitialAssignmentCalculator.java, src/pujaSah/InitialAssignmentCalculator3.java, src/pujaSah/InitialAssignmentDayIndex.java, src/pujaSah/InitialAssignmentNumberAddition.java, src/pujaSah/InitialAssignmentNumberCount.java, src/pujaSah/InitialAssignmentNumberDivisibility.java, src/pujaSah/InitialAssignmentNumberSystem.java, src/pujaSah/InitialAssignmentPrimeNumber.java, src/pujaSah/InitialAssignmentQuarterIndex.java, src/pujaSah/InitialAssignmentStudentInfo.java, src/pujaSah/InitialAssignmentStudentInfo2.java, src/pujaSah/InitialAssignmentStudentTestResult.java
Output1:
Output2:
Output3:
Output4:
Output5:
Output6:
Output7:
Output8:
Output9:
Output10:
Output11:
Output12:
Output13:
=> Submitted all initial assignments

src/apurvaBabel/Assignment10.java
=> Assignment10_ApurvaB

src/saroj/Last3NumbersDivisibleBy3And7.java
=> Assignment10_Saroj_Last 3 numbers divisible by 3 and 7

src/pujaSah/Last3NumberDivisibilityBy3And7.java
=> Please review today's Assignment10_PujaSah_30Aug

src/sagarY/InterestaAndTemp.java
=> Assignment11_SagarY added

src/kiran/DivNum.java, src/kiran/DivNumLast2.java
=> Assignment_10_kiran

src/chaitanyaMankar/Assignment10.java
=> Assignment10 Added

src/sagarY/DivisibleBy3And7Last.java
=> Assignment10_SagarY

src/shubhamG/Divisiblity.java
=> Assignment10_ShubhamG

src/jagruti/Assignment10_JagrutiM.java
=> Assignment10_JagrutiM

src/shivaniGour/Last3Numbers.java
=> Assignment 10 added

src/gauravSahu/Simpleinterest.java
**Assignment - 11 : 30th Aug'2022**
Please create new branch for below assignment.
Create two parameterized methods in same class. 
Write a method to compute simple interest   
Simple Interest = (P x T x R)/100 
Where, 
P is the principle amount 
T is the time [year] and 
R is the rate
Write a method to convert temperature from Fahrenheit to Celsius degree.
Celsius = (fahrenheit - 32) * 5 / 9
Note : double data type can store decimal numbers.
Assignment - 11 : 30th Aug'2022
Please create new branch for below assignment.
Create two parameterized methods in same class. 
Write a method to compute simple interest   
Simple Interest = (P x T x R)/100 
Where, 
P is the principle amount 
T is the time [year] and 
R is the rate
Write a method to convert temperature from Fahrenheit to Celsius …
=> Assignment 11 on Simple Interest & Celcius Farenheit

src/monali/Assignment11.java
=> Assignment11 added

src/gauravSahu/Div3and7.java, src/gauravSahu/Whileloop.java
**Assignment - 10** 
Assignment - 10 : 30th Aug'2022
Find last 3 numbers divisible by 3 and 7.
Input : 10 to 200
Output : 189
168
147   
**Snap :**
=> Assignment on last 3 numbers divisible by 3 and 7

src/monali/Modular.java
=> 10th Assignment

src/harshalRane/SimpleInterest.java
=> Assignment11_Harshal

src/pallaviRaut/CalTempInterest.java
=> Assignment 11 added for conversion

src/apurvaBabel/Assignment11.java
=> Assignment11_ApurvaB

src/pallaviRaut/NumDivisibily3and7.java
=> Assignment 10  last 3 Numbers divisible by 3 and 7

src/niveditaGavade/LoopEx1.java
=> Assignment10_Nivedita

src/kiran/Ex11.java
=> Assignment_11_Kiran

src/shubhamG/Assignment11.java
=> Assignment11_ShubhamG

src/shivaniGour/Computation.java
=> Assignment 11 added

src/ankitaBarwad/Interest_ConvertTemp.java
=> Assignment11_AnkitaB

src/hardikBhatia/Assignment10.java
Assignment-10 Last 3 and second last number division by 3 & 7
=> Assignment-10 Last 3 and second last number division by 3 & 7

src/priyankaD/ParameterizedMethods.java
=> Assignment_11_Priyanka

src/anujaD/DivisibleNumber.java
=> Assignment10_Anuja

src/manjiri/Assignment10_1.java
=> Assignment10_Manjiri

src/priyankaD/Last3NoDivBy3and7.java
=> Assignment_10_Priyanka

src/asthaSrivastava/PrintLast3Number.java
=> Assignment10_Astha

src/smitaVetal/LastDivisible.java, src/smitaVetal/SimpleInterest.java
=> Assignment_10_Smita

src/ojaswini/DayIndex.java, src/ojaswini/DayIndex2.java
=> Assignment_4.1_ojaswini

src/jagruti/Assignment11_JagrutiM.java
=> Assignment11_JagrutiM

src/vibhaS/Assignment10.java
=> Assignment10_vibha

src/maheshSantoki/Mathemetics.java
Assignment 11
Simple interest
fahrenheit to celsius
=> Assignment_11_MaheshS

src/deepakPatil/Assignment11.java
=> Assignment 11

src/deepakPatil/LoopBreakAssignment.java
=> Assignment10 deepak p

src/maheshSantoki/ForLoopEx3.java
=> Assignment10a_MaheshS

src/anujaD/Simpleinterest.java
=> Assignment11_Anuja

src/swapnilMaheshwari/Last3NumberDivisableBy3and7.java, src/swapnilMaheshwari/SecondLastNumDivisableBy3and7.java, src/swapnilMaheshwari/SecondLastNumDivisiableBy3and7.java
program 1 - Last 3 number divisible by3and 7
Program 2 - 2nd last number which is divisible by 3 and 7
=>  Assignment 10 Programms for review

src/smitaVetal/LastDivisible.java
=> Assignment_11_Smita

src/akankshaVyas/Last3NumDivisibleBy3n7.java, src/akankshaVyas/SecondLast.java
=> Assignment10_AkankshaVyas

src/pankajBhatt/CalculateSimpleInterest.java
=> PankajBhattAssignment11_30thAug2022

src/hindaviIngle/NumDivBy3N7.java
=> Assignment01_Hindavi

src/pankajBhatt/Assignment10_30thAug2022.java
=> Assignment 10 30thAug2022

src/harshadaJagtap/Interest_Temp.java
=> Assignment_11_HarshadaJ

src/vibhaS/Assignment11.java
=> Assignment11_vibha

src/narendraD/CalulateSimpleInterestAndTemperatureUnitConverter.java
Assignment 11: Simple Interest & Temperature SS-
=> Assignment_11_Simple Interest & Temperature Conversion_Narendra

src/narendraD/ToDisplayDivisibleByNumbersInReverseOrder.java
Assignment No. 10: To display divisible by numbers in reverse order:
=> Assignment10 narendra

src/deepakBorse/Assignment10_Last3Div3and7.java, src/deepakBorse/ProgrammingTest1.java
=> Assignment10_DeepakB

src/nehaniG/Divisibility.java
=> Assignment10.1_Nehanig

src/mohiniA/Assignment10.java
=> Assignment10

src/shivaniLikhia/ConvertTemperature.java, src/shivaniLikhia/SimpleInterest.java
=> Assignment11_ShivaniLikhia

src/pranjaliV/Assignment10Pranjali.java
=> Assignment_10_Pranjali

src/sanket/ForLoopEx4.java
=> Assignment10_Sanket submitted

src/sanket/Calculation.java
=> Assignment11_Sanket

src/chaitanyaMankar/BankingSystem.java, src/chaitanyaMankar/PrimeNumberWithMethods.java
=> Assignment12_Chaitanya

src/apurvaBabel/Assignment12.java
=> Assignment12_ApurvaB

src/harshalRane/BankingSystem1.java
Assignment 13 Harshal - 1st Sept
Main Method Code:
=> Assignment13_Harshal

src/pujaSah/MethodsOnPrimeNumber.java
=> Assignment_12_PujaSah_1stSep

src/harshalRane/PrimeNumbersParam.java
Assignment12_Harshal - 1st Sept
=> Assignment12_Harshal

src/pujaSah/SimpleInterestAndTemperatureConversion.java
=> Assignment_11_PujaSah_30Aug

src/shridharKumbhar/SKRAssignment10.java
=> Shridhar Assignment 10

src/asthaSrivastava/FindSiAndConvertTemp.java
Updated variable names in small.
=> Assignment11_Astha1

src/komalShrivastava/Last3NosDivBy3And7.java, src/komalShrivastava/SimpleInterestandTemperature.java
=> Assignment11 komal

src/komalShrivastava/Last3NosDivBy3And7.java
=> Assignment10 komal

src/amrutaSagne/FindReverseNumbers.java
=> Assignment11_Amruta

src/amrutaSagne/Calculation.java
=> Assignment10_Amruta

src/aishwaryaPawar/Test1.java
=> Test1_AishwaryaP

src/abhijeet/SimpleIntAndConvertTemp.java
=> Assignment11_AbhijeetM

src/abhijeet/Last3DivisibleBy3And7.java
=> Assignment10_AbhijeetM

src/akankshaSharma/InterestCalculation.java
=> Assignment11-29August2022

src/akankshaSharma/DivisibilityBy3And7.java
=> Assignment 10 -29August2022

src/nehaniG/Assignment11.java
=> Assignment11_Nehani

src/hemanshi/Assignment11.java, src/hemanshi/Last3Digit.java
=> Assignment_30

src/nikeshM/Division1.java, src/nikeshM/SimpleInterest.java, src/nikeshM/Temperature.java
=> 30th_Aug_assignment_Nikesh

src/chaitanyaMankar/PrimeNumberWithMethods.java
=> PrimeNumberWithMethods

src/nehaniG/PrimeNumberParamethod.java
=> Assignment12 nehanig

src/priyankaD/BankOperations.java
=> Assignment_13_Priyanka

src/vibhaS/Assignment_12.java
=> Assignment12_vibha

src/shubhamG/PrimeNumbersInfo.java
=> Assignment12_ShubhamGupta

src/sanket/BankFacility.java
Assignment 13 Bank System Results
=> Assignment13_Sanket_BankSystem

src/maheshSantoki/BankSystem.java, src/maheshSantoki/PrimeNumber2.java
Bank System:
Output of Bank System:
=> Assignment 13 mahesh s

src/maheshSantoki/PrimeNumber2.java
Assignment 12 -Mahesh Santoki
1.find prime numbers
2.count prime numbers
3.sum of prime numbers
4.average of prime numbers
=> Assignment_12_MaheshS

src/sanket/FindPrimeNumber.java
Assignment12 Prime Number Result:
=> Assignment12_Sanket_FindPrimeNumber

src/manjiri/BankingSys.java, src/manjiri/PrintPrimeNumbers.java
Banking Sys: Output
Prime Number: Output
=> Assignment12_13-Manjiri

src/sagarY/Bank.java
=> Assignment13_SagarY

src/nehaniG/BankSystem.java
=> Assignment13_Nehani

src/vibhaS/Assignment13.java
=> Assignment13_vibha

src/anujaD/PrimeNumber.java, src/anujaD/PrintprimeNumber.java
=> Assignment12_Anuja

src/sagarY/PrimeShow.java
=> Assignment12_SagarY

src/swatiM/SimpleInterest.java
=> Assignment11_Swati

src/swatiM/PrintLastThreeNumbers.java
=> Assignment10_Swati

src/adittyThakare/Assignment12.java, src/adittyThakare/Assignment13.java
=> Assignment12-13_Aditty

src/niveditaGavade/PrimeNumbers.java
=> Assignment12_Nivedita

src/niveditaGavade/InterestAndTemp.java
=> Assignment11_Nivedita

src/swatiM/BankingSystem.java
=> Assignment13_Swati

src/shubhamG/BankingSystem.java, src/shubhamG/PrimeNumbersInfo.java
=> Assignment13 shubham g

src/rohanNaik/PrimeOperations.java
=> Assignment12_Rohan

src/pankajBhatt/PrimeNumberOperations.java
=> PankajBhatt_Assignment12_1Sep2022

src/shraddhaRekhate/PrimeNumberWithMethods.java
=> Assignment12_Shraddha

src/ankitaBarwad/PrimeNumberMethod.java
=> Assignment12_AnkitaB

src/shridharKumbhar/Test1Shridhar.java
=> Test1 Shridhar

src/saroj/PrimeNumberCalculation.java
=> Assignment12_Saroj prime number calculation

src/ankitaBarwad/BankDetailsMethod.java
=> Assignment13_AnkitaB

src/amolMule/PrimeRange.java
=> Assignment 12 added

src/komalShrivastava/BankingSystem.java
=> Assignment13_Komal

src/asthaSrivastava/PrimeNoFromRange.java
=> Assignment12_Astha

src/akankshaVyas/PrimeNumOperations.java
=> Assignment12_AkankshaVyas

src/pankajBhatt/BankingSystem.java
=> Pankaj bhatt assignment13 1 sep2022

src/shridharKumbhar/Assignment_10_Shridhar.java
1) Assignment 10 - last 3 no divisible by 3& 7 between 10and 200
=> Assignment 10 last no divisible by 3& 7 bet 10 and 200

src/ankitaBarwad/LastThreeNumbers.java
=> Assignment10_AnkitaB

src/smitaVetal/PrimeNumbers.java
=> Assignment12_Smita

src/swapnilMaheshwari/PrimeNumInRangeOptimized.java, src/swapnilMaheshwari/PrimeNumberInRange.java
=> Assignment 12 submitted

src/akankshaSharma/Banking.java, src/akankshaSharma/Prime.java
**Assignment 12 Prime numbers:**
**Assignment 13 Banking operations:**
=> Assignments 12 and 13_01 sep 2022_Akanksha_Sharma

src/titikshaG/Banking.java
public class Banking {
int debit;
int credit;
static int balance;
int bal=10000;
static int totaldebit;
static int totalcredit;
void debitCount(int amount)
{
bal=bal-amount;
debit++;
totaldebit++;
}
void creditCount(int amount)
{
bal=bal+amount;
credit++;
totalcredit++;
}
void printBalance()
{
System.out.println("total balance is" +" "+ bal);
balance++;
}
void individualTransaction()
{
System.out.println("Customer number of times amount debited is" +" "+ debit);
System.out.println("Customer number of times amount credited is"+" " +credit);
}
void finalBalance()
{
balance=debit-credit;
}
void totalTransaction()
{
System.out.println("Total number of amount debited is : " + totaldebit);
System.out.println("Total number of amount credited is : " + totalcredit); …
=> test3_titiksha

src/niveditaGavade/BankTransactions.java
=> Assignment13_Nivedita

src/titikshaG/Prime.java
public class Prime
{
int count;
int sum;
int average;
void checkPrime(int num)
{
boolean primeFlag=true;
for(int index=2;index<=num/2;index++)
if(num%index==0)
{
primeFlag=false;
break;
}
if(primeFlag==true)
{
System.out.println(num +" "+ "is a prime number");
}
count++;
sum=sum + num;
average= sum/count;
}
void printPrime(int start,int end)
{
for (int num=start;num<=end;num++)
{
checkPrime(num);
}
}
void display()
{
System.out.println(count +" "+ "is count of Prime numbers");
System.out.println(sum +" "+ "is sum of Prime numbers");
System.out.println(average +" "+ "is average of Prime numbers");	
}
public static void main(String[] a)
{
Prime prime=new Prime();
prime.printPrime(100,120);
prime.display();
}
}
=> test2_titiksha

src/shridharKumbhar/Assignment_11_Shridhar.java
=> Assignment 11 Shridhar Percentage ang F to C converter

src/asthaSrivastava/BankOperations.java
=> Assignment13_Astha

src/harshadaJagtap/FirstProg.java, src/harshadaJagtap/HiDay.java, src/harshadaJagtap/PrimeNumbers.java, src/harshadaJagtap/PrintBankDetails.java
Program1 PrimeNumberS:
Program2 BankDetails:
=> Assignment_12_HarshadaJ

src/deepakBorse/PrimeNumberwithMethods.java
=> Assignment11_DeepakB

src/pranjaliV/assignment12/PrimeNumber.java
=> Assignment_12_Pranjali

src/titikshaG/Primenumber.java
public class Primenumber
{
int count=0;
void start5Number(int num)
{
boolean primeFlag=true;
for(int index=2;index<=num/2;index++)
{
if(num%index==0)
{
primeFlag=false;
break;				
}
}
if (primeFlag==true)
{
count++;
System.out.println(num +" "+"Number is prime");	
}
}
void printPrimeNumber(int iteration)
{
int num=2;
while(num>=2 && count!=iteration)
{
start5Number(num);
++num;
}
}
public static void main(String[] a)
{
Primenumber primenumber=new Primenumber();
primenumber.printPrimeNumber(5);
}
}
=> Test4_Titiksha

src/akankshaVyas/basicExamples/Calculator.java, src/akankshaVyas/basicExamples/CalculatorParameter.java, src/akankshaVyas/basicExamples/Day.java, src/akankshaVyas/basicExamples/DivisibleBy3n7.java, src/akankshaVyas/basicExamples/Example1.java, src/akankshaVyas/basicExamples/Example2.java, src/akankshaVyas/basicExamples/Example4.java, src/akankshaVyas/basicExamples/Last3NumDivisibleBy3n7.java, src/akankshaVyas/basicExamples/Quater.java, src/akankshaVyas/basicExamples/Result.java, src/akankshaVyas/basicExamples/SecondLast.java, src/akankshaVyas/basicExamples/Student.java, src/akankshaVyas/basicExamples/StudentInfo.java, src/akankshaVyas/basicExamples/Week.java, src/akankshaVyas/forLoopPrimeBanking/Bank.java, src/akankshaVyas/forLoopPrimeBanking/BankingSystem.java, src/akankshaVyas/forLoopPrimeBanking/ForEx.java, src/akankshaVyas/forLoopPrimeBanking/PrimeNum.java
=> Assignment13 akanksha vyas

src/anujaD/Bank.java
=> Assignment13_Anuja

src/sanket/NPrimeNumber.java
=> Assignment_14_Sanket

src/asthaSrivastava/WhileExPrimeNumber.java
=> Assingment14_Astha

src/shubhamG/PrimeNumberWhileLoop.java
=> Assignment14_shubham

src/hemanshi/Assignment13.java
=> Assignment_13

src/ankitaBarwad/PrimeNumberUsingWhile.java
=> Assignment14_AnkitaB

src/pranjaliV/assignment12/BankDetails.java
=> Assignment_13_Pranjali

src/gauravSahu/Banking.java
Assignment 13 : Create a Banking System which has the following functionality.
Code :
=> Banking System with user details, transction history

src/smitaVetal/PrintPrime.java
=> Assignment14_Smita

src/aishwaryaPawar/Prime2.java
=> Assignment12_AishwaryaP

src/pranjaliV/assignment14/PrimeNumber.java
=> Assignment_14_Pranjali

src/manjiri/assignments/AdvancedCalculator.java, src/manjiri/assignments/Assignment10_1.java, src/manjiri/assignments/BankingSys.java, src/manjiri/assignments/Calculator.java, src/manjiri/assignments/DayIndentifier.java, src/manjiri/assignments/ExamResult.java, src/manjiri/assignments/FindQuarter.java, src/manjiri/assignments/FirstProg.java, src/manjiri/assignments/IndetifyWeekdaysOrWeekend.java, src/manjiri/primenumbers/PrimeNumber.java, src/manjiri/primenumbers/PrimeNumbersWhileLoop.java, src/manjiri/primenumbers/PrintPrimeNumbers.java
=> Assignment14-Manjiri Restructing

src/shridharKumbhar/SKRAssignment12.java
=> Assignment 12 Shridhar Prim Number

src/deepakPatil/WhileLoopPrime.java
=> Assignment 14

src/saroj/FirstNPrimeNumber.java
=> Assignment14 saroj

src/deepakPatil/BankSystem.java, src/deepakPatil/PrimeNumberParam.java
=> Assignment 12 and 13

src/deepakBorse/Assignments/Assignment14_PrimeNo.java, src/deepakBorse/Assignments/BankDetails.java, src/deepakBorse/Assignments/CalculatorPara.java, src/deepakBorse/Assignments/Calender.java, src/deepakBorse/Assignments/Example4.java, src/deepakBorse/Assignments/PrimeNumberwithMethods.java, src/deepakBorse/Assignments/StudentInfo.java, src/deepakBorse/Assignments/StudentResult.java, src/deepakBorse/Practice/FirstProg.java, src/deepakBorse/Practice/WhileLoopEx1.java, src/deepakBorse/Practice/package-info.java
=> Assignment14_DeepakB

src/chaitanyaMankar/NprimeNumber.java
=> N Prime Assignment Updated

src/harshalRane/primeNumber/PrimeNumber.java, src/harshalRane/primeNumber/PrimeNumberWithMethods.java, src/harshalRane/primeNumber/PrintNum.java
=> Package_Files_Modified

src/shrutiArora/Bank.java, src/shrutiArora/Calculator.java, src/shrutiArora/ParametrisedCalci.java, src/shrutiArora/ProcessIndex.java, src/shrutiArora/Score.java, src/shrutiArora/StudentInfo.java
=> Assignment1_6_shruti

src/hindaviIngle/BankingSystem.java, src/hindaviIngle/PrimeNumberRange.java, src/hindaviIngle/SimpleInterest.java
=> Assignment 12_13_Hindavi

src/amolMule/BankSystem.java
Assignment 13_AmolB
For Bank Details updates
=> Assignment 13_Bank details updated

src/swapnilMaheshwari/Assignment1/Example1.java, src/swapnilMaheshwari/Assignment1/Example2.java, src/swapnilMaheshwari/Assignment1/Example3.java, src/swapnilMaheshwari/NprimeNumber.java, src/swapnilMaheshwari/NprimeNumberOptimized.java
=> Assignment 14 changes

src/komalShrivastava/WhileLoop.java
=> Assignment14_Komal

src/shrutiArora/ProgrammingTest_1.java
=>  ProgrammingTest_1_shruti

src/rahulSaswadkar/PrimeWithWhile.java
=> Assignment14 rahul

src/rahulSaswadkar/Bank.java
=> Assignment13_Rahul

src/akankshaVyas/forLoopPrimeBanking/PrimeNumOperations.java, src/akankshaVyas/forLoopPrimeBanking/PrintPrimeNumByWhileLoop.java
Created counting using while loop and also write method to find prime number using for and while loop
=> Assignment14_AkankshaVyas

src/vibhaS/Assignment14.java
=> Assignment14_vibha

src/apurvaBabel/Assignment14_PrimeNumWhileLoop.java
=> Assignment14_ApurvaB

src/shrutiArora/Assignment10Last3Num.java, src/shrutiArora/Assignment11SimpleInterst.java, src/shrutiArora/Assignment12PrimeNumOp.java, src/shrutiArora/Assignment13.java, src/shrutiArora/Assignment14.java, src/shrutiArora/Assignment9Prime.java, src/shrutiArora/LoopExample.java
=> Assignment7_14_shruti

src/mohiniA/Loop/TestDivide.java, src/mohiniA/Parameter/CalculatorPara.java, src/mohiniA/Parameter/SimpleIntrest.java, src/mohiniA/Parameter/Temperature.java, src/mohiniA/basic/Calculator.java, src/mohiniA/basic/Example1.java, src/mohiniA/basic/ExampleStatic.java, src/mohiniA/basic/Index.java
=> Assignment11

src/hindaviIngle/BankingSystem.java, src/hindaviIngle/FirstNPrimeNumber.java, src/hindaviIngle/PrimeNumberRange.java, src/hindaviIngle/SimpleInterest.java
=> Assignment 14 hindavi

src/pankajBhatt/Assignent13_2Sep2022.java
=> PankajBhatt_Assignent13_2Sep2022

src/shivaniGour/BankingSystem.java
=> Assignment13 shivani gour

src/rashmiG/staticAssignments/BankingSystem.java
=> Assignment13_RashmiG

src/manjiri/Test/Test2.java
=> Test2-Manjiri

src/shubhamG/Test2.java
=> Test2_ShubhamG

src/nehaniG/Test_2.java
=> Test_2_Nehanig

src/adittyThakare/basicconcepts/Test2.java
=> Test2_Aditty

src/mohiniA/Loop/FindNumber.java
=> Test find num

src/shraddhaRekhate/Num.java
=> Assignment_14_ShraddhaR

src/sagarY/PrimeList.java, src/sagarY/WhileLoop.java, src/sagarY/whileLoop/WhileEx2.java
=> Test2_sagarY0409

src/shrutiArora/ProgrammingTest2.java
=> ProgrammingTest2_shruti

src/vibhaS/Test2.java
=> Test2_vibha

src/akankshaVyas/Test/FindRequiredNumForSumByWhile.java
=> Test2.AkankshaVyas

src/deepakPatil/WhileLoopTest2.java
=> Test 2 while loop target number

src/apurvaBabel/Test2.java
=> Test2_ApurvaB

src/ankitaBarwad/WhileLoopExample.java
=> Test2_AnkitaB

src/maheshSantoki/LoopExamples/WhileLoopEx1.java
Test2_4th_sep_MaheshS :
#find the required numbers for given target Sum of numbers.
=> Test2_4th_sep_MaheshS

src/pujaSah/assignments11_20/FindSumUsingWhileLoop.java
=> Assignment_15_Puja_Sah_04Sep

src/komalShrivastava/Test2.java
=> Test2_Komal

src/chaitanyaMankar/Test2.java
=> Test2 Assignment added

src/harshalRane/Tests/FindNumbers.java
=> Test2_Harshal

src/deepakBorse/Assignments/Test2.java, src/deepakBorse/Practice/IncreDecre.java, src/deepakBorse/Practice/IncreDecre2.java
=> Test2_DeepakB

src/pranjaliV/Test2/RequiredNumbers.java
=> Test2 pranjali

src/smitaVetal/SumOfNumbers.java
=> Test2_Smita

src/pankajBhatt/Test2WhileLoop.java
=> PankajBhatt_Test2_WhileLoop_4Sep2022

src/shivaniGour/PrimeNoWhile.java
=> Assignment14 First N Prime

src/kiran/Ex15.java
=> Assignment15_kiran

src/sanket/Test2.java
=> Test2_Sanket

src/monikaDwivedi/PrimeNumber.java
=> Assignment_8_9_MonikaDwivedi

src/akankshaVyas/Return_type/PrimeWithReturnType.java
=> Assignment15_AkankshaVyas

src/apurvaBabel/Assignment15_PrimeNumReturnType.java
=> Assignment15_ApurvaB

src/shivaniLikhia/FindNum.java
=> Assignment14_ShivaniL

src/nehaniG/SumOfPrimeNumbers.java
=> Assignment15_Nehanig

src/vinod/Test14.java
=> Required number

src/adittyThakare/basicconcepts/SumOfPrimeNumbers.java
Assignment 15 -> Addition of first n prime numbers:
=> Assignment15_Aditty

src/nikitaPhase/Assignment_28_aug.java, src/nikitaPhase/PrimeNumAssignment_14.java
=> Assignment 28 aug

src/aditiIngle/Assign_11_ParameterisedMethod.java, src/aditiIngle/Assign_12_PrimeNumbers.java, src/aditiIngle/Assign_13_BankingSystem.java, src/aditiIngle/Assignment_10_DivBy3and7.java, src/aditiIngle/Test2_RequiredCount.java
Aditi_Assignment_10:
Aditi_Assignment_11:
Aditi_Assignment_12:
Aditi Assignment_13:
Aditi_test2_04thSept:
=> Aditi_Assignments_10_11_12_13_test2

src/hemanshi/Test2.java
=> Test2_hemanshi

src/hemanshi/PrimeNumWhileLoop.java
=> Assignment_14

src/harshalRane/Tests/Test2_Practise.java, src/harshalRane/practise/HappyTeachersDay.java
=> Practice Package created

src/pujaSah/assignments11_20/PrimeNumbersWithReturnStatement.java
=> Please review Assignment_16_PujaSah_5Sep

src/harshalRane/Tests/FindNumbers.java, src/harshalRane/Tests/Test2_Practise1.java
=> Test2 harshal

src/swatiM/tests/FindNumbers.java, src/swatiM/tests/Test1.java
=> Test2_Swati

src/rashmiG/programmingTestPrograms/Test1DivisibleBy3And7.java, src/rashmiG/programmingTestPrograms/Test2MinimunNumbersSum.java
=> Test1_Test2_RashmiG

src/swapnilMaheshwari/Assignment15/SumOfCount.java
=> Asignment15

src/amolMule/FirstNPrime.java, src/amolMule/FirstSumFifty.java
=> Test Programm added_FirstSum50

src/shivaniGour/RequiredNosSum.java
=> Test2 shivani gour

src/titikshaG/Totalcount.java
public class Totalcount 
{
void processData(int num)
{
int count=0,sum=0,index=1;
while(num>sum)
{
sum=index+sum;
count++;
index++;
}
System.out.println("Total count is:"+" "+count);
System.out.println("Loop ran till:"+" "+ sum);
System.out.println("Index value is:" + " " +index);
}
public static void main(String[] a) 
{
Totalcount totalcount=new Totalcount();
totalcount.processData(50);
}
}
=> test5_titiksha

src/akankshaSharma/Test2/Test2.java
=> Test 2_Akanksha Sharma_4sep2022

src/pujaSah/assignments11_20/StringMethods.java
=> Assignment 16 puja sah 6 sep

src/adittyThakare/basicconcepts/Assignment16.java
Assignment 16 : Program to find string length and middle character
=> Assignment16_Aditty

src/harshadaJagtap/LoopExapmples/FindPrime.java, src/harshadaJagtap/LoopExapmples/FirstPrimeNumbers.java, src/harshadaJagtap/LoopExapmples/For_Loops.java, src/harshadaJagtap/LoopExapmples/Loop1.java, src/harshadaJagtap/LoopExapmples/Loop2.java, src/harshadaJagtap/LoopExapmples/Loop3.java, src/harshadaJagtap/LoopExapmples/Loop4.java, src/harshadaJagtap/LoopExapmples/LoopEx10.java, src/harshadaJagtap/LoopExapmples/PrimeNumber.java, src/harshadaJagtap/LoopExapmples/PrimeNumbers.java, src/harshadaJagtap/LoopExapmples/Required_Numbers.java, src/harshadaJagtap/basic_programms/Calculator1.java, src/harshadaJagtap/basic_programms/Example1.java, src/harshadaJagtap/basic_programms/Interest_Temp.java, src/harshadaJagtap/basic_programms/Student.java, src/harshadaJagtap/basic_programms/calculator.java, src/harshadaJagtap/if_condition/BankDetails.java, src/harshadaJagtap/if_condition/Day.java, src/harshadaJagtap/if_condition/Day1.java, src/harshadaJagtap/if_condition/Day2.java, src/harshadaJagtap/if_condition/HiDay.java, src/harshadaJagtap/if_condition/PrintBankDetails.java, src/harshadaJagtap/if_condition/Results.java, src/harshadaJagtap/increment_decrement/Increment_Decrement.java
=> Assignment_15_HarshadaJ

src/amolMule/Assignment15.java
Assignment 15 for return statement done
=> Assignement15_AmolB_Return added

src/aditiIngle/PrimeReturn.java
=> Aditi_Assignment_15_return

src/shivaniGour/FirsNPrimeSum.java
=> Assignment 15 added

src/hardikBhatia/FivePrimeNumberSumReturnType.java
=> prime number with return of sum

src/pranjaliV/assignment15/PrimeNumber.java
=> Assignment15 pranjali

src/harshalRane/Assignments/FirstNPRimeNumbersWithReturn.java
=> Assignment15_Harshal_FirstNPrimeNumbers_WithReturnType

src/swapnilMaheshwari/IncrementDecrement.java, src/swapnilMaheshwari/NprimeNumberUsingFunction.java
=> Assignment16_SwapnilM

src/manjiri/ReturnTypeEx1.java
=> Assignmenmt15-Manjiri

src/vibhaS/Assignment16.java
=> Assignment16_vibha

src/nehaniG/Assignment11to15/Test_2.java, src/nehaniG/NameOperation.java
=> Assignment16_NehaniG

src/komalShrivastava/ReturnSumPrimeNumber.java, src/komalShrivastava/WhileLoop.java
=>  Assignment15_Komal and updated variable name in WhileLoop.java file

src/harshalRane/Assignments/Assignment15/Assignment16LengthChar.java
=> Assignment16_Harshal

src/kiran/StringTest1.java
=> Assignment16_kiran

src/titikshaG/Primenumberwithreturntype.java
public class Primenumberwithreturntype 
{
int index=2;
int sum=0;
int count=0;
int primeNo(int num)
{
boolean flag = true;
while (count!=num)		
{
for(int i=2;i<index;i++)
{
if(index%i==0)
{
flag=false;
break;
}
}
if (flag==true)
{
System.out.println("prime numbers are "+ index);
count++;
sum=sum+index;
}
index++;
flag=true;
}
return sum;
}
public static void main(String[] a)
{
Primenumberwithreturntype retuntype=new Primenumberwithreturntype();
int pm=retuntype.primeNo(5);
System.out.println("sum of prime number is: "+ pm);
}
}
=> Test6_Titiksha

src/shubhamG/Assignment11to20/ReturnPractice.java
=> Assignment16_ShubhamG

src/maheshSantoki/returnTypeExample/LengthOfString.java
Assignment--16
[image](https://user-images.githubusercontent.com/102714496/188636251-6f39d1f0-55d5-4c38-a611-da079980a341.png)
=> Assignment_16_MaheshS

src/asthaSrivastava/GetNameLength.java, src/asthaSrivastava/PrimeNumberReturn.java
=> Assignment16 astha

src/chaitanyaMankar/StringReturn.java
String Function using Return Assignment.
Please review
=> Return String Assignment added

src/komalShrivastava/StringFunctions.java
=> Assignment16_Komal

src/sagarY/returnType/ReturnType.java, src/sagarY/returnType/ReturnType1.java
=> Assignment 15and16 sagarY

src/jagruti/Assignment13_JagrutiM.java, src/jagruti/Assignment14_JagrutiM.java
=> Assignment13_JagrutiM

src/titikshaG/Lengthofnumber.java
public class Lengthofnumber {
int lenghthOfStr(String str)
{
return str.length();
}
char m1(String str){
int length=str.length();
int index=0;
if(length %2 ==0) {
index=length/2-1;
}
else {
index=length/2;
}
return str.charAt(index);
}
void display(String str) {
int length=lenghthOfStr(str);
System.out.println("The length of string is "+ length);
char middlename=m1(str);
System.out.println("The middle letter of" +" "+ str+" "+ "is"+" "+ middlename);
System.out.println("--------------------------------------------");
}
public static void main(String[] args)
{
Lengthofnumber len=new Lengthofnumber();
len.display("Maulik");
len.display("Technocredit");
len.display("Titiksha");
}
}
=> Test7_titiksha

src/shivaniGour/ReturnStatement.java
=> Assignment16 Added

src/saroj/BankingSystemUpdated.java, src/saroj/SimpleInterest.java
=> Assignment11 saroj

src/saroj/BankingSystemUpdated.java
=> Updated Banking system

src/hardikBhatia/Assignment16.java
=> Assignment 16 Hardik

src/akankshaVyas/ReturnType/ReturnStringLength.java
=> Assignment16_AkankshaVyas

src/saroj/SumOfPrimeNumber.java
=> Assignment15_Saroj

src/smitaVetal/LengthCharReturn.java
=> Assignment_16_Smita

src/smitaVetal/Practice.java, src/smitaVetal/ReturnPrimeNum.java
=> Assignment_15_Smita

src/swapnilMaheshwari/LenAndMidCha.java
=> Assignment 16 changes

src/hardikBhatia/Assignment14PrimeNumber.java
=> Assignment14_Hardik_Prime_Number_While

src/manjiri/ReturnTypeEx2.java
=> Assignment16-Manjiri

src/vibhaS/Assignment17.java
=> Assignment17_vibha

src/jagruti/Bank.java, src/jagruti/CalculatorWithParameter.java, src/jagruti/Example4.java, src/jagruti/PrimeNumber.java
=> CalculatorWithParameter

src/amrutaSagne/Assignment16.java
=> Assignment16

src/amolMule/LengthStr.java
=> AmolB_Assignment 16 done

src/swatiM/assignments/StringLength.java, src/swatiM/assignments/SumOfPrimeNumbers.java
=> Assignment16 swati

src/swatiM/assignments/SumOfPrimeNumbers.java
=> Assignment15_Swati

src/pranjaliV/assignment16/MiddleChar.java
=> Assignment_16_Pranjali

src/asthaSrivastava/returnType/GetNameLength.java, src/asthaSrivastava/returnType/PrimeNumberReturn.java
Added new package returnType for Return Type Assignments.
=> Sept6_PackageReturn_Astha

src/harshalRane/Assignments/assignment17MultipleStringOperations/Assignment17.java, src/harshalRane/practise/Test2_Practise1.java
=> Assignment17_Harshal

src/apurvaBabel/Assignment17.java
=> Assignment17_ApurvaB

src/harshalRane/practise/Test2_Practise1.java, src/narendraD/BankTransactions.java, src/narendraD/TogetPrimeNumbersCount.java
=> Assignment_12_Narendra

src/nilamP/PrimeNumber.java
=> Assignment_12_sept_2

src/nehaniG/NameOperation2.java
=> Assignment17_Nehanig

src/chaitanyaMankar/StringFunctionsReturn.java
=> Assignment17 Added

src/adittyThakare/stringoperations/Assignment16.java, src/adittyThakare/stringoperations/Assignment17.java
=> Assignment17_Aditty

src/rashmiG/primeNumber/SumOfFirstNPrimeNosReturnKeyword.java
=> Assignment14.1_RashmiG

src/pujaSah/assignments11_20/CountDigitsInString.java, src/pujaSah/assignments11_20/EvenPositionCharInReverse.java, src/pujaSah/assignments11_20/EvenPositionCharacter.java, src/pujaSah/assignments11_20/ReverseOfString.java, src/pujaSah/assignments11_20/SumDigitsInString.java
output1:
output2: 
output 3:
output 4:
output 5:
=> Please review Assignment_17_PujaSah_7Sep

src/apurvaBabel/Assignment16_ReturnLengthAndMiddleName.java
rectified as per comments on PR 488
=> Assignment16_rectified as per comments

src/shivaniLikhia/CountDigits.java, src/shivaniLikhia/EvenPositionCharacter.java, src/shivaniLikhia/ReturnReverse.java, src/shivaniLikhia/ReverseEvenPositionCharacter.java, src/shivaniLikhia/SumOfDigits.java
=> Assignment17_ShivaniL

src/swapnilMaheshwari/StringOperations.java
=> Assignment 17 changes

src/hindaviIngle/SumOfFirst5PrimeReturn.java
=> Assignment 15 hindavi

src/rohanNaik/Assignments/Assignment15PrimeSum.java
=> Assignment15_SumOfPrime_Rohan

src/ankitaBarwad/ReverseStringExample.java
=> Assignment17_AnkitaB

src/anujaD/ReturnTypeEx1.java
=> Assignment16_Anuja

src/rohanNaik/Assignments/Assignment16Char.java, src/rohanNaik/Assignments/Assignment17String.java
=> Assignment17_String_RohanN

src/komalShrivastava/StringFunctionsWithReturn.java
=> Assignment17_Komal

src/shubhamG/Assignment11to20/StringPractice.java
=> Assignment17_Shubham

src/kiran/StringTest2.java
=> Assignment17_kiran

src/sanket/StringOperations.java
=> Assignment17_Sanket

src/saroj/stringPrograms/NameLength.java
=> Assignment 16 saroj

src/deepakBorse/Assignments/Assignment17StringOps.java
=> Assignment17_DeepakB

src/hardikBhatia/Assignment17StringReverseCharAt.java
=> Assignment17 String Reverse CharAt

src/maheshSantoki/returnTypeExample/RevreseString.java
=> Assignment-17_07th_Sep_MaheshS

src/rashmiG/StringProgramsAssignments/StringOperations.java
=> Assignment16_RashmiG

src/swatiM/assignments/string/Stringoperations.java
=> Assignment17_Swati

src/manjiri/StringEx/StringEx1.java, src/manjiri/StringEx/StringEx2.java
=> Assignment17-Manjiri

src/harshalRane/Tests/FindNumbers.java, src/sagarY/StringAndChar/ReturnType2.java, src/sagarY/returnType/ReturnType2.java
=> Assignment17 sagar y

src/shrutiArora/Assignment15.java, src/shrutiArora/Assignment16.java, src/shrutiArora/Assignment17.java, src/shrutiArora/Assignment18.java
=> Assignment15_18_shruti

src/rashmiG/primeNumber/Assignment14FirstNPrimeNos.java
=> Assignment14.2_RashmiG

src/rashmiG/Last3NosDivisibleBy3And7.java, src/rashmiG/Modulation.java
=> Assignment10_11_RashmiG

src/ashishBramhe/A10_Last3DivisibleBy3_7.java, src/ashishBramhe/A1_Calculator.java, src/ashishBramhe/A2_CalculatorEnhanced.java, src/ashishBramhe/A3_Bank.java, src/ashishBramhe/A4_DayType.java, src/ashishBramhe/A4_FindDayFromIndex.java, src/ashishBramhe/A4_Quarter.java, src/ashishBramhe/A5_StudentDetails.java, src/ashishBramhe/A5_StudentResult.java, src/ashishBramhe/A6_EvenOddForLoopExamples.java, src/ashishBramhe/A7_ParameterizedMethodExamples.java, src/ashishBramhe/A8_PrimeNumber.java
=> Assignment1_10_Ashish

src/rahulSaswadkar/StringProgram1.java
=> Assignment16_Rahul

src/sanket/StringOperationsAdvance.java
=> Assignment18_Sanket

src/pranjaliV/assignment18/StringAssignment2.java
=> Assignment 18 pranjali

src/chaitanyaMankar/String/StringOperations.java, src/chaitanyaMankar/String/StringUsingCharacter.java
=> String Operations using Character added

src/swapnilMaheshwari/StringRearrange.java
=> Assignment 18 changes pushed

src/swapnilMaheshwari/StringOperations.java
Optimized the code and removed unnecessary line of code.
=> optimized the code

src/rahulSaswadkar/StringProgram2.java
=> Assignment17_Rahul

src/akankshaVyas/StringOperation/StringOperation.java
Highlighted output for odd position print and adding+2 in index for even logic
=> Assignemnt17_AkankshaVyas

src/adittyThakare/stringoperations/Assignment18.java
=> Assignment18_Aditty

src/harshalRane/Assignments/assignment18_rearrangeFrequency/Assignment18FindFrequencyOfChar.java, src/harshalRane/Assignments/assignment18_rearrangeFrequency/Assignment18RearrangeAndFindFrequency.java, src/harshalRane/Assignments/assignment18_rearrangeFrequency/Assignment18RearrangeString.java, src/harshalRane/Assignments/assignment18_rearrangeFrequency/Assignment18RearrangeString2.java
Assignment18_Harshal
1) Write a program to rearrange String in given format. 
String str = "te2cH4no";
output : "24tecHno";
Hint : AllDigitAllCharacter
-------------------------------------------
2) Write a program to rearrange String in given format. 
Hint : Uppercase letters + digits + LowerCase letter
input = "t8EcHNo5Cred3iTs";
output : EHNCT853tcoredis 
---------------------------------------------
3) Find frequency of given character from given String. 
String str = "TechnoTtcredits";
char targetChar = 't';
output : 4
=> Assignment18_Harshal

src/chiragPatel/Assignment_17.java
=> Assignment 17

src/ashishBramhe/A11_ParameterizedMethodExample.java
=> Assignment11_Ashish

src/rashmiG/StringMethodOPerations.java
=> Assignment17_RashmiG

src/asthaSrivastava/string/StringValidation.java
=> Assignment17_Astha

src/titikshaG/Reversenumber.java
public class Reversenumber {
String reverName(String name) {
String revName="";
for(int index=name.length()-1;index>=0;index--)
{
revName=revName+name.charAt(index);
}
return revName;
}
String modularWithTwo(String name) {
String odIndex="";
for(int index=name.length()/2;index>0;index = index-2)
{
odIndex=odIndex+name.charAt(index);
}
return odIndex;
}
String oddIndexPosition(String name) {
String odIndex="";
for(int index=1;index<name.length();index = index+2)
{
odIndex=odIndex+name.charAt(index);
}
return odIndex;
}
String reverseOfOddIndex(String name) {
String odIndex="";
for(int index=name.length()-1;index>0;index = index-2)
{
odIndex=odIndex+name.charAt(index);
}
return odIndex;
}
int countOfNumbers(String name) {
int count = 0;
for (int index = 0; index < …
=> Test8_Titiksha

src/nikeshM/Return/ReturnMethod.java, src/nikeshM/prime/AssignmentReturn.java, src/nikeshM/prime/FirstPrime.java, src/nikeshM/prime/FourtPrime.java
=> 1st to 6th_Sep_assignment_Nikesh

src/amolMule/Assignment15.java, src/amolMule/stringProg/StrRev.java
=> Assignment17_AmolB_String program added

src/harshadaJagtap/StringExamples/Example3.java, src/harshadaJagtap/StringExamples/Example4.java, src/harshadaJagtap/StringExamples/Example5.java, src/harshadaJagtap/StringExamples/Example6.java, src/harshadaJagtap/StringExamples/Example7.java, src/harshadaJagtap/return_type/Example2.java, src/harshadaJagtap/return_type/Return_String.java
=> Assignment_16_HarshadaJ

src/gauravSahu/PrimeN.java
Print first N prime numbers.
Sorry for late submission.
=> N Primenumber assignment

src/apurvaBabel/Assignment18.java
=> Assignment18_ApurvaB

src/jagruti/Assignment15.java, src/jagruti/Assignment16.java
=> Assignment15and16_JagrutiM

src/swatiM/assignments/StringLength.java
=> Assignment16_Swati- updated code

src/deepakPatil/FirstNPrimeSumReturn.java
=> Assignment number 15

src/maheshSantoki/returnTypeExample/RearangeString.java
=> Assignment_18_MaheshS

src/shivaniLikhia/FindFrequency.java, src/shivaniLikhia/RearrangeString.java, src/shivaniLikhia/RearrangeUpperLowerDigit.java
=> Assignment18_ShivaniL

src/nilamP/StringOperation2.java
=> Assignment_18_Nilam

src/saroj/stringPrograms/RearrangeString.java
=> Assignment_18_Saroj

src/pujaSah/assignments11_20/FrequencyOfLettersInString.java, src/pujaSah/assignments11_20/OperationsOnStringClassMethods.java
=> Please Review Assignment_18_PujaSah_8Sep

src/komalShrivastava/FrequencyOfCharacter.java, src/komalShrivastava/RearrangeString.java, src/komalShrivastava/RearrangeString2.java
Assignment 18: String & Character Functions
Program 1: Program to rearrange String in Digits+Characters format.
Program 2: program to rearrange String in Uppercase letters + digits + Lowercase letter format.
Program 3: Program to find frequency of given character from given String.
=> Assignment18 Komal

src/sagarY/StringAndChar/StringAndCharMethods.java
=> Assignment18_sagarY

src/hardikBhatia/Assignments/Assignment10.java, src/hardikBhatia/Assignments/Assignment14PrimeNumber.java, src/hardikBhatia/Assignments/Assignment16.java, src/hardikBhatia/Assignments/Assignment18StringRearrangeFrequency.java, src/hardikBhatia/Assignments/Assignment4DayWeekdaysQuaterCheck.java, src/hardikBhatia/Assignments/Assignment7.java
=> assignment 18 string rearrange frequency

src/hemanshi/MiddleName.java, src/hemanshi/ReturnLength.java
(1)getNameLength
(2)getMiddleChar
=> Assignment_16

src/nehaniG/NameOperation3.java
=> Assignment18_Nehanig

src/monikaDwivedi/Assignments/Assignment_28_aug.java, src/monikaDwivedi/Assignments/Bank.java, src/monikaDwivedi/Assignments/BankDetails.java, src/monikaDwivedi/Assignments/Calculator.java, src/monikaDwivedi/Assignments/FindWeekdaysWeekend.java, src/monikaDwivedi/Assignments/NumGame.java, src/monikaDwivedi/BankingSystemAssignment13.java, src/monikaDwivedi/InterviewQ1.java, src/monikaDwivedi/PrimeNumberAssignment12.java, src/monikaDwivedi/StringMethod.java
=> Assignment12MonikaD

src/rashmiG/StringProgramsAssignments/CharacterAndStringOperations.java
=> Assignment18_RashmiG

src/hindaviIngle/StringOperation2.java
=> Assignment_18_Hindavi

src/ankitaBarwad/Rearrange_FindFrequency_String.java
=> Assignment18_AnkitaB

src/anujaD/StringProg.java
=> Assignmet17_Anuja

src/swatiM/assignments/Stringoperations8Sep.java
=> Assignment18_Swati

src/akankshaVyas/StringOperation/StringFormatting.java
=> Assignment18_AkankshaVyas

src/shubhamG/Assignment11to20/StringPractice2.java
=> Assignment18_Shubham

src/rahulSaswadkar/PrimeWithWhileAndReturn.java
=> Assignment15_Rahul

src/mohiniA/Loop/FindNumber.java, src/mohiniA/Parameter/PrimeParameter.java, src/mohiniA/ReturnType/CharDigitSum.java, src/mohiniA/ReturnType/PrimeNumSumReturn.java, src/mohiniA/ReturnType/StringReturn.java
=> Assignments14_15_16_17

src/deepakBorse/Assignments/Assignment18StringOps2.java, src/deepakBorse/Practice/Access.java, src/deepakBorse/Practice/Stringpractice.java
=> Assignment18_DeepakB

src/asthaSrivastava/returnType/RearrangeString.java
=> Assignment18_Astha

src/sagarY/Arrays/ArrayBasics.java
=> Assignment19_sagarY

src/pranjaliV/assignment19/ArrayAssignment.java
=> Assignment_19_Pranjali

src/komalShrivastava/ArrayGames.java
=> Assignment19_Komal_ArrayOperations

src/vibhaS/Assignment19.java
=> Assignment19_vibha

src/harshalRane/Assignments/assignment18_rearrangeFrequency/Assignment18FindFrequencyOfChar.java, src/harshalRane/Assignments/assignment18_rearrangeFrequency/Assignment18RearrangeAndFindFrequency.java, src/harshalRane/Assignments/assignment18_rearrangeFrequency/Assignment18RearrangeString2.java
=> Modified_Assignment18

src/akankshaVyas/StringOperation/StringOperation.java
Second and third line output is extra because of two more method odd calling  and even calling with +2
=> Assignemnt17_new_AkankshaVyas

src/amolMule/stringProg/RearrangeStr.java, src/amolMule/stringProg/SumDigitStr.java
Assignment 18 and 17 prog are added
=> Assignment 18 added for string

src/deepakPatil/StringClassExample2.java
=> Assignment 18

src/ashishBramhe/A12_PrimeOperations.java
=> Assignment12_Ashish

src/titikshaG/Arrangingstrings.java
public class Arrangingstrings {
String getRearranging(String name)
{
String tempDigit="";
String tempLetter="";
for(int index=0;index < name.length()-1;index++) {
char ch=name.charAt(index);
if(Character.isLetter(ch)) {
tempLetter=tempLetter+ch;}
else if(Character.isDigit(ch))
{
tempDigit=tempDigit+ch;
}
}
return tempDigit + tempLetter;
}
String getUpperCase(String name)
{
String tempDigit="";
String tempUpperLetter="";
String tempLowerLetter="";
for(int index=0;index < name.length()-1;index++) {
char ch=name.charAt(index);
if(Character.isUpperCase(ch)) {
tempUpperLetter=tempUpperLetter+ch;}
else if(Character.isDigit(ch))
{
tempDigit=tempDigit+ch;
}
else if(Character.isLowerCase(ch))
{
tempLowerLetter=tempLowerLetter+ch;
}
}
return tempUpperLetter + tempDigit + …
=> Test9_Titiksha

src/monikaDwivedi/BankingSystem.java
=> Assignment13MonikaD

src/gauravSahu/String4.java
=> Assignment_17_String

src/adittyThakare/arrayoperations/Assignments19.java
=> Assignment19 aditty

src/shubhamG/Assignment11to20/ArrayPractice.java
=> Assignment19_Shubham

src/saroj/arrayPrograms/ArrayActivity.java
=> Assignment19_Saroj arrayActivity

src/gauravSahu/StringReturn.java
**NOTE : Not able to attach the png file here so pasted my code with o/p.**
package gauravSahu;
public class StringReturn2 {
int getstringlength(String name) {
return name.length();
}
char getMidddleChar(String name) {
int length = name.length();
int index = 0;
if (index % 2 == 0) {
index = length / 2 - 1;
} else {
index = length / 2;
}
return name.charAt(index);
}
public static void main(String[] args) {
String name = "Gaurav";
System.out.println(name.length());
StringReturn2 s1 = new StringReturn2();
char name1 = s1.getMidddleChar("Gaurav");
System.out.println(name1);
char name2 = s1.getMidddleChar("Technocredits");
System.out.println(name2);
}
}
OUTPUT: 
6
r
u
=> String length & Middle char using return

src/pujaSah/OperationsOnArray.java
=> Please review Assignment_19_PujaSah_9Sep

src/sanket/ArrayOperationsEx1.java
Assignment 19 Array Operations Result:
=> Assignment19_ArrayOperations_Sanket

src/chaitanyaMankar/Array/PrimeSum.java
=> Assignment19_ChaitanyaM

src/maheshSantoki/arrayExamples/Assignment19Array.java, src/maheshSantoki/arrayExamples/package-info.java
=> Assignment_19_9Sept_MaheshS

src/nehaniG/ArrayOperations.java
=> Assignment19_Nehanig

src/shrutiArora/Assignment19.java
=> Assignment_19_shruti

src/shrutiArora/ProgrammingTest_3.java
=>  ProgrammingTest_3_Shruti

src/shrutiArora/ProgrammingTest_4.java
=>  ProgrammingTest_4_Shruti

src/shrutiArora/Assignment20.java
=> Assignment20_shruti

src/gauravSahu/String18Assign.java
=> Assignment_18_Gaurav

src/kiran/ArrayTest1.java
=> Assignment19_kiran

src/ankitaBarwad/ArrayExample.java
=> Assignment19_AnkitaB

src/namratamishra/Calculator.java
=> namrtamishra_assignment1

src/sohail/array/ArrayMax.java, src/sohail/array/ArrayMin.java, src/sohail/array/ArrayPrime.java, src/sohail/array/ArrayString.java, src/sohail/array/ArraySum.java, src/sohail/stringprograms/ArrayLengthMax.java, src/sohail/stringprograms/ArrayMiddleCharater.java
=> Assignment_19_Sohail

src/mohiniA/StringArray/Assign17_18_19/ArrayOpration19.java, src/mohiniA/StringArray/Assign17_18_19/StringOperation17.java, src/mohiniA/StringArray/Assign17_18_19/StringOpration18.java
Assignment 17:
Assignment 18:
Assignment 19:
=> Assignment17_18_19

src/hardikBhatia/Assignments/Assignment17StringReverseCharAt.java, src/hardikBhatia/Assignments/Assignment19Array.java
=> Assignment19_hardik_array

src/manjiri/StringEx/StringEx3.java, src/manjiri/StringEx/StringEx4.java, src/manjiri/StringEx/StringEx5.java, src/manjiri/arrayEx/ArrayEx1.java, src/manjiri/arrayEx/ArrayEx2.java, src/manjiri/arrayEx/ArrayEx3.java, src/manjiri/arrayEx/ArrayEx4.java, src/manjiri/arrayEx/ArrayEx5.java, src/manjiri/arrayEx/ArrayEx6.java
ArrayEx1:
ArrayEx2:
ArrayEx3:
ArrayEx4:
ArrayEx5:
=> Assignment19-Manjiri

src/swapnilMaheshwari/ArrayPrograms/MaxAndMinNumberInArray.java, src/swapnilMaheshwari/ArrayPrograms/MiddleCharInArray.java, src/swapnilMaheshwari/ArrayPrograms/SumOfArrayElements.java, src/swapnilMaheshwari/ArrayPrograms/SumOfPrimeNumberUsingArray.java
Sum of Array -
Sum of Prime Number -
Max and Min number in array -
Middle Character in the array
=> Assignment 19 programs

src/jagruti/Assignment17.java
=> Assignment17_New

src/harshadaJagtap/StringExamples/Example10.java, src/harshadaJagtap/StringExamples/Example8.java, src/harshadaJagtap/StringExamples/Example9.java
Program 1:
Program 2:
Program 3:
=> Assignment_18_HarshadaJ

src/hemanshi/String1.java, src/hemanshi/String2.java, src/hemanshi/String3.java
=> Assignment_19

src/saroj/testPrograms/MiddleCharacterArray.java
git push --set-upstream origin Test3_Saroj
=> Test3_Saroj

src/namratamishra/Basic_Operations/Calculator_parameterized.java
=> namratamishra_assignment2_calculator_parameterized

src/akankshaVyas/Arraypkg/MaxNumInArray.java, src/akankshaVyas/Arraypkg/MiddleCharacterOfArray.java, src/akankshaVyas/Arraypkg/SumOfPrimeNumOfArray.java, src/akankshaVyas/Arraypkg/SumofArray.java
=> Assigment19_AkankshaVyasArray

src/deepakPatil/ArrayDemo.java
=> Assignment19 Deepak Patil

src/hardikBhatia/Test/Test3.java
=> Test3_Hardik

src/smitaVetal/ArrayHandling2.java, src/smitaVetal/ArrayTest.java
Program 1 output -
program 2 output -
=> Test_Smita_10Sep

src/nehaniG/Test3.java, src/nehaniG/Test3_2.java
=> Test3_Nehanig

src/shraddhaRekhate/StringExample2.java
=> Assignmen_17_ShraddhaR

src/nilamP/ArrayOperations.java
=> Assignment19_Nilam

src/harshadaJagtap/Array/Exampe1.java, src/harshadaJagtap/Array/Example2.java, src/harshadaJagtap/Array/Example3.java, src/harshadaJagtap/Array/Example4.java, src/harshadaJagtap/Array/Example5.java
=> Assignment_19_HarshadaJ

src/ankitaBarwad/Test3_MiddleCharacter.java
=> Test3_AnkitaB

src/shivaniGour/Test3MiddleChar.java
=> Added Test 3

src/shubhamG/Test3Program1.java, src/shubhamG/Test3Program2.java
=> Test3_Program1&2_Shubham

src/adittyThakare/arrayoperations/Test3_Program1.java, src/adittyThakare/arrayoperations/Test3_Program2.java
Test3 Program 1:
Test3 Program 2:
=> Test3_Aditty

src/smitaVetal/ArrayBasic.java, src/smitaVetal/ReturnPrimeNum.java
=> Assignment_19_Smita

src/shivaniGour/ArrayAssignment19.java
=> Added Assignment 19
