KrishnaKTechnocredits/JAVATechnoAug2022

src/rahulSaswadkar/ArrayProgram1.java

Assignment19_Rahul

---

src/asthaSrivastava/arrayBasics/ArrayBasics.java

Assignment19_Array_Astha

---

src/shivaniGour/Assignment18.java

Assignment 18 added

---

src/shivaniGour/StringOperation.java

Added Assignment 17

---

src/gauravSahu/Array1.java

Assignment - 19 : 9th Sep'2022
1) Write a method to return sum of all numbers in given array.
input : {10,11,15}
output : 36
2) Write a method to return sum of all prime numbers from given array.
input : {11,14,17,22,44}
output : 28
Hint : (11+17 = 28)
3) Write a method to return max number from array.
input : {11,4,55,23,43}
output : 55
4) Write a method to return min number from array.
input : {11,4,55,23,43}
output : 4
5) Write a method to print middle character of all array elements.
input : {"Ashish","Aditty","Manjiri","Ankita"}
output : Ashish -> h
Aditty -> i
Manjiri -> j
Ankita -> k

Array_Assignment

---

src/rahulSaswadkar/StringProgram2.java
src/rahulSaswadkar/StringProgram3.java

Assignment18_Rahul

---

src/asthaSrivastava/string/RearrangeString.java

Moved file from Package 'returnType' to 'string'

Assignment19_Astha

---

src/hindaviIngle/ArrayOperations.java

Assignment_19_Hindavi

---

src/swatiM/assignment/arrayPrograms/ArrayLengthAndMiddleChar.java
src/swatiM/assignments/stringProgram/StringLength.java
src/swatiM/assignments/stringProgram/Stringoperations.java
src/swatiM/assignments/stringProgram/Stringoperations8Sep.java
src/swatiM/tests/Test3Array.java

Test3 swati

---

src/swatiM/assignment/arrayPrograms/ArrayLengthAndMiddleChar.java
src/swatiM/assignments/stringProgram/StringLength.java
src/swatiM/assignments/stringProgram/Stringoperations.java
src/swatiM/assignments/stringProgram/Stringoperations8Sep.java

Assignment19_Swati

---

src/gauravSahu/Array20.java
src/gauravSahu/Array20Test2.java

Assignment_Test1_Test2_20

---

src/deepakBorse/Assignments/Test3_midcharMaxlen.java

Test3-DeepakB

---

src/nikeshM/ReturnTypeNikesh/DigitCount.java
src/nikeshM/ReturnTypeNikesh/DigitSum.java
src/nikeshM/ReturnTypeNikesh/EvenReturn.java
src/nikeshM/ReturnTypeNikesh/EvenReverse.java
src/nikeshM/ReturnTypeNikesh/Return.java

Assignment_17_Nikesh

---

src/titikshaG/Medialcharacter.java

//Return middle character of max length String from given array.
//input : {"Krishna","Maulik","Aashvi","Technocredits","Harsh"}
//output : c
public class Medialcharacter {
String getMedialArray(String[] name)
{ 
int midLength=name[0].length();
for(int index=0;index<name.length;index++)
{
if(midLength<=name[index].length())
{
name[0]=name[index];
}
}
return name[0];
}
char getMiddleCharacter(String[] str){ 
String input=getMedialArray(str);
int index=0;
if (input.length()%2==0) {
index=(input.length()/2-1);
}
else{
index=(input.length()/2);
}
char ch=(input.charAt(index));
return ch;
}
//Write a method to return middle character of each elements from given array.
//input : {"Mahesh","Avni","Puja","Harshal","Aditty","Rahul"}
//output : Mahesh -> h
// Avni -> v
// Harshal …

Test 3_Titiksha

---

src/apurvaBabel/Test3.java

Test3_ApurvaB

---

src/pranjaliV/Tests/Test3.java

Test_3_Pranjali

---

src/vibhaS/Test3.java

Test3_vibha

---

src/kiran/ArrayTest2.java

Assignment20_kiran

---

src/maheshSantoki/arrayExamples/MiddleCharOfMaxLengthString.java

Test_3_10sept_MaheshS

---

src/shivaniLikhia/MiddleCharOfMaxLengthString.java

Test3_ShivaniL

---

src/shivaniLikhia/FindMaxAndMinInArray.java
src/shivaniLikhia/FindMiddleCharInArray.java
src/shivaniLikhia/SumOfNumInArray.java
src/shivaniLikhia/SumOfPrimeNumInArray.java

Assignment19 shivani l

---

src/pujaSah/assignments11_20/middleCharInEachStringOfAnArray.java
src/pujaSah/assignments11_20/middleCharOfMaxLengthString.java

Test3 puja sah 10 sep

---

src/akankshaVyas/Test/MaxStringLengthName.java

Tried output from Arrays.toString() method as well

Test3.AkankshaVyas

---

src/manjiri/Test/Test3.java
src/manjiri/Test/Test3_2.java
src/manjiri/Test/Test3_Client.java

Test3-Manjiri

---

src/komalShrivastava/Test3a.java
src/komalShrivastava/Test3b.java

Program 1 :
Return middle character of max length String from given array.
input : {"Krishna","Maulik","Aashvi","Technocredits","Harsh"}
output : c 
Program 2:
Write a method to return middle character of each elements from given array

Test3 komal

---

src/hindaviIngle/FindMiddleCharacter.java
src/hindaviIngle/MiddleCharOfMaxLength.java

Test3_Hindavi

---

src/deepakBorse/Assignments/Assignment19Array.java
src/deepakBorse/Practice/ArrayExample.java

Assignment19_DeepakB

---

src/shraddhaRekhate/Assignments/StringAssignment18.java

StringAssignment18.java

---

src/nilamP/Test3.java

Test3_Nilam

---

src/titikshaG/Practisearray.java

//Write a method to return sum of all numbers in given array.
//input : {10,11,15}
//output : 36
public class Practisearray {
int sumOfArray(int[] num)
{
int sum=0;
for(int index=0;index<num.length;index++)
{
sum=sum+num[index];
}
return sum;
}
//Write a method to return sum of all prime numbers from given array.
//input : {11,14,17,22,44}
//output : 28
//Hint : (11+17 = 28)
boolean primeNumber(int num)
{
boolean flag=false;
for(int index=2;index<num/2;index++)
{
if(num%2==0)
{
flag=true;
}
else {
flag=false;}
}
return flag;
}
int sumOfPrimeNumber(int[] num)
{
int sum=0;
for(int index=0;index<num.length;index++)
{
boolean flag=primeNumber(num[index]);
if(flag)
{
sum=sum+num[index];
}
}
return sum;
}
//Write a method to return max number from array.
//input : …

Assignment_19_Titiksha

---

src/nikeshM/StringCode/FrequencyOfCharacter.java
src/nikeshM/StringCode/StringFormat.java
src/nikeshM/StringCode/StringRearrange.java

Assignment_18_Nikesh

---

src/sanket/ArrayTest3.java

Test3 array sanket

---

src/ankitaBarwad/Test4Prg1_ArrayDigitSum.java
src/ankitaBarwad/Test4Prg2_TreeCount.java

Program 1 Output : 
Program 2 Output :

Test4_AnkitaB

---

src/nehaniG/Test4.java
src/nehaniG/Test4_1.java

Test4_Nehanig

---

src/rahulSaswadkar/ArrayProgram2.java

Test3_Rahul

---

src/amolMule/arrayss/ArrayOpr.java

Assignment 19 added for arrays

---

src/nilamP/Test_4.java

Test4_Nilam

---

src/shubhamG/Assignment11to20/ArrayPractice.java
src/shubhamG/Assignment11to20/ArrayPractice2.java

Assignment20_Shubham

---

src/hemanshi/Test_3.java

Test3_Hemanshi

---

src/sanket/ArrayOperationsEx2.java
src/sanket/ArrayTest4.java

Assignment20 sanket

---

src/sanket/ArrayTest4.java

Test4_Array_Sanket

---

src/anujaD/StringProgrm.java

Assignment18_Anuja

---

src/gauravSahu/ArrayTest4.java
src/gauravSahu/ArrayTest4B.java

ArrayTest 4A & 4B

---

src/shridharKumbhar/Assignment_18.java

Assignment 18 Shridhar

---

src/asthaSrivastava/assignments/CountOfTrees.java
src/asthaSrivastava/assignments/SumOfDigitsFromString.java

Sept11_Test4_Astha

---

src/titikshaG/Visibletreeheight.java

//suppose you are standing in front of line of trees with different heights now requirement is to find how many trees are visible
import java.util.Arrays;
public class Visibletreeheight {
int numberOfTreesVisible(int[] num)
{
int maxHeigth=num[0];
int count=1;
for(int index=0;index<num.length;index++) {
if(num[index]>maxHeigth)
{
maxHeigth=num[index];
count++;
}
}
return count;
}
public static void main(String[] args)
{
Visibletreeheight visibletreeheight=new Visibletreeheight();
int input[]={3,5,11,9,10,13};
System.out.println(Arrays.toString(input));
int output=visibletreeheight.numberOfTreesVisible(input);
System.out.println("Total number of trees visible:"+" " +output);
System.out.println();
int[] input2={3,5,4};
System.out.println(Arrays.toString(input2));
int …

Test_4_Titiksha

---

src/chaitanyaMankar/String/CountVisibleTree.java
src/chaitanyaMankar/String/ReturnNumInString.java

Test4_ChaitanyaM

---

src/hindaviIngle/SumOfDigitArray.java
src/hindaviIngle/TreeProgramFromMastercard.java

Test4_Hindavi

---

src/sagarY/test4sept11/CountOfVisibleTrees.java
src/sagarY/test4sept11/SumOfDigitsOfEachStringInAnArray.java

Please review:
Program:1
Program:2

Test4_sagarY1109

---

src/adittyThakare/arrayoperations/Test4_Program1.java
src/adittyThakare/arrayoperations/Test4_Program2.java

Test4 Program1:
Test4 Program2:

Test4_Aditty

---

src/harshalRane/Tests/Test4Program1SumOfAllDigitsInNamesArray.java
src/harshalRane/Tests/Test4Program2ReturnCountOfVisibleTrees.java

Test4_Program 1:
Program 1 :
Test4_Program 2:

Test4_Harshal

---

src/chaitanyaMankar/Array/ReturnMiddleChar.java
src/chaitanyaMankar/Array/StringOpsUsingArray.java

Test3_ChaitanyaM

---

src/asthaSrivastava/arrayBasics/ArrayOperations.java
src/asthaSrivastava/arrayBasics/GetMiddleChar.java

Sep10_Test3_Astha

---

src/smitaVetal/ArraySumDigit.java
src/smitaVetal/VisibleTrees.java

Test4_Smita

---

src/manjiri/Test/Test4.java
src/manjiri/Test/Test4_2.java
src/manjiri/Test/Test4_Client.java

Test4.java and Test4_Client.java:
Test4_2.java:

Test4-Manjiri

---

src/vibhaS/test/Test4.java

Test4_vibha

---

src/pranjaliV/Test2/Test4Pranjali.java

Test 4 p ranjali

---

src/komalShrivastava/Test4a.java
src/komalShrivastava/Test4b.java

Program 1 :
Write a method to return sum of all the digits present in each elements from given array.
input : {"Ma1he4sh","A9vni","P1uj3a5","Harshal","A4d4itty","Rahul"}
output : Mahesh -> 5
Avni -> 9
Puja -> 9
Harshal -> 0
Aditty -> 8
Rahul -> 0
Program 2 : Return count of visible trees

Test4_Komal - 2 Programs

---

src/apurvaBabel/Test4_Program1.java
src/apurvaBabel/Test4_Program2.java

Test4_ApurvaB

---

src/deepakPatil/Assignment20ArrayExamples/ArrayAssignment20_1.java
src/deepakPatil/Assignment20ArrayExamples/ArrayAssignment20_2.java
src/deepakPatil/Assignment20ArrayExamples/ArrayAssignment20_3.java

Assignment 20 DeepakP

---

src/pankajBhatt/Assignment18_9_Sep2022.java

PankajBhatt_Assignment_18_9_Sep2022

---

src/aditiIngle/Assign_18_RearrangeString.java

Assignment_18_AditiI

---

src/pankajBhatt/Assignment17_8_Sep2022.java

PankajBhatt_Assignment_17_8_Sep2022

---

src/pankajBhatt/Assignment16_7_Sep2022.java

PankajBhatt_Assignment_16_7_Sep2022

---

src/pankajBhatt/Assignment15_6_Sep2022.java

PankajBhatt_Assignment_15_6_Sep2022

---

src/pankajBhatt/Assignment14_5_Sep2022.java

PankajBhatt_Assignment_14_5_Sep2022

---

src/rahulSaswadkar/ArrayProgram3.java

Assignment20_Rahul

---

src/adittyThakare/arrayoperations/Assignment20.java

Assignment20_Aditty

---

src/deepakBorse/Assignments/Test4.java

Test4_DeepakB

---

src/maheshSantoki/arrayExamples/Test4Array.java
src/maheshSantoki/arrayExamples/VisibleTrees.java

Test_4_MaheshS

---

src/hardikBhatia/Test4.java

Test_4_Hardik

---

src/deepakPatil/ProgTest3_1.java
src/deepakPatil/ProgTest3_2.java

Test 3 DeepakP

---

src/rashmiG/assignment20ArrayAndStringPrograms/DifferenceOfEvenOddSum.java
src/rashmiG/assignment20ArrayAndStringPrograms/MaximumLengthName.java
src/rashmiG/assignment20ArrayAndStringPrograms/SumOfAllEvenNumbersInArray.java
src/rashmiG/assignment20ArrayAndStringPrograms/SumOfNonPrimeNumbersArray.java
src/rashmiG/assignment20ArrayAndStringPrograms/SumOfNonPrimeNumbersDivisibleBy5And7Array.java
src/rashmiG/assignment20ArrayAndStringPrograms/VowelCountArray.java
src/rashmiG/assignment20ArrayAndStringPrograms/VowelCountInString.java

Program1:
Program2:
Program3:
Program4:
Program5:
Program6:
Program7:

Assignment20_RashmiG

---

src/kiran/ArrayTest4.java

Assignment21_kiran

---

src/komalShrivastava/ArrayFunctions.java

Assignment20_Komal

---

src/deepakPatil/Test4/Test4_1.java
src/deepakPatil/Test4/Test4_2.java

Test4_DeepakP

---

src/hemanshi/Test4.java

Test4_Hemanshi

---

src/harshalRane/Assignments/assignment20/Assignment20Program1.java
src/harshalRane/Assignments/assignment20/Assignment20Program2.java
src/harshalRane/Assignments/assignment20/Assignment20Program3And4.java
src/harshalRane/Assignments/assignment20/Assignment20Program5And6.java
src/harshalRane/Assignments/assignment20/Assignment20Program7.java

Assignment20_Program1
Program 2:
Program 3 and 4:
Program 5 and 6:
Program 7:

Assignment20_Harshal

---

src/vinod/Assignment/Array18.java

Aiisgnment18programe

---

src/amolMule/TestArray.java

Test3 Added for Arrays

---

src/shridharKumbhar/assignment19Array/MaxNumArray.java
src/shridharKumbhar/assignment19Array/MiddleCharacterInArray.java
src/shridharKumbhar/assignment19Array/MinNumInArray.java
src/shridharKumbhar/assignment19Array/SumOfAllNum.java
src/shridharKumbhar/assignment19Array/sumOfPrimeNumInArray.java

1) Sum of number
2) Sum of prime number
3)Minimum no in given array
4)Max number
5)middle character

Assignment 19 package added and 5 assignments class under it

---

src/vinod/Assignment/Assignment17.java

Assignment17

---

src/hemanshi/Assignment13.java
src/hemanshi/Assignment_20.java

Assignment_20

---

src/rahulSaswadkar/ArrayProgram4.java

Test4_Rahul

---

src/pankajBhatt/Test_4_Prog_2_11_Sep2022.java

Pankaj_Bhatt_Test4_Program_2_11_Sep2022

---

src/pankajBhatt/Test_4_Prog_1_11_Sep2022_TreeVisibleOrNot.java

Pankaj_Bhatt_Test4_11_Sep2022

---

src/pankajBhatt/Test3_10_Sep2022.java

Pankaj_Bhatt_Test3_10_Sep2022

---

src/mohiniA/ArrayOprationTest4.java

Test4Array_Mohini

---

src/swatiM/tests/Test4.java

Test4_Swati

---

src/amolMule/array2/ArrayOprns.java
src/amolMule/array2/CountVowels.java

Programs for arrays (Part 1)
Programs for arrays (Part 2)

Assignment 20 is added

---

src/shivaniGour/Test4Array.java

Added Test 4 ShivaniGour

---

src/nikeshM/ArrayCode/ArrayAddition.java
src/nikeshM/ArrayCode/ArrayPrimeNumber.java
src/nikeshM/ArrayCode/MaximumNumber.java
src/nikeshM/ArrayCode/MiddleCharacter.java
src/nikeshM/ArrayCode/MinimumNumber.java

Assignment_19_Nikesh

---

src/asthaSrivastava/arrayBasics/EvenAndOddNum.java
src/asthaSrivastava/arrayBasics/SumOfNonPrime.java
src/asthaSrivastava/arrayBasics/SumOfNonPrimeAndDiv.java
src/asthaSrivastava/arrayBasics/Vowels.java

Assignment20_Astha

---

src/nehaniG/Assignment20.java

Assignment20_Nehani1

---

src/vibhaS/Assignment/Assignment20.java
src/vibhaS/Assignment/Assignment20_1.java

Assignment20_vibha

---

src/swapnilMaheshwari/Test3/MidChrOfMaxLenStr.java
src/swapnilMaheshwari/Test3/MiddleCharFromName.java

Program 1 - Return middle character of max length String
Program 2 -

Test3_SwapnilM

---

src/shubhamG/Assignment21to30/ArrayPractice3.java

Assignment21_Shubham

---

src/shrutiArora/Assignment21.java

Assignment_21_shruti

---

src/chaitanyaMankar/ArrayZero.java
src/chaitanyaMankar/SecondMax.java

SecondMax using Return

---

src/ashishBramhe/A13_BankOperations.java

Assignment13_Ashish

---

src/hardikBhatia/Assignments/Assignment23.java

Assignment23_hardik

---

src/pranjaliV/assignment21/SecondHighestAssignment21.java

Assignment_21_Pranjali

---

src/swapnilMaheshwari/Test4/SumOfAllDigitsFromArray.java
src/swapnilMaheshwari/Test4/TreeVisibility.java

Test4_SwapnilM

---

src/sanket/ArrayOperationsEx6.java

Assignment25_Sanket

---

src/nilamP/StringOperations4.java

assignment25_Nilam

---

src/smitaVetal/Assignment25.java

Assignment25_Smita

---

src/akankshaVyas/Interview/Interview1.java

Interview.1_AkankshaVyas

---

src/shubhamG/Assignment21to30/RepeatedWordInStrinig.java

Assignment25_Shubham

---

src/jagruti/Assignmen19/MaxNumberFromArray.java
src/jagruti/Assignmen19/MinNumberFromArray.java
src/jagruti/Assignmen19/PrintMiddleCharacterOfArray.java
src/jagruti/Assignmen19/SumOfNumbersArray.java
src/jagruti/Assignmen19/SumOfPrimeNumbersArra.java

Assignment19_Jagruti

---

src/jagruti/Assignment18/FinalAssignment18.java
src/jagruti/Assignment18/FrequencyOfCharacter.java
src/jagruti/Assignment18/RearrangeString.java
src/jagruti/Assignment18/RearrangeString2.java

Assignment18_jagruti

---

src/harshalRane/Assignments/assignment25PrintRepeatedWords/Assignment25.java

Assignment25_Harshal

---

src/asthaSrivastava/arrayBasics/SumOfNumbers.java

Assignment24_Astha

---

src/swapnilMaheshwari/Assignment22/ArrayIndexUpdate.java

Assignment22_SwapnilM

---

src/nehaniG/Assignment23.java

Assignment23_Nehanig

---

src/hardikBhatia/Assignments/Assignment13.java
src/hardikBhatia/Assignments/Assignment24.java

**Assignment-24 Output**
**Assignment-13 missed**

Assignment24_13_Hardik

---

src/akankshaVyas/ArrayWork/CountVowelString.java
src/akankshaVyas/ArrayWork/DifferenceNum.java
src/akankshaVyas/ArrayWork/MaxLengthName.java
src/akankshaVyas/ArrayWork/SumNonPRimeNumAndDivisibilty.java
src/akankshaVyas/ArrayWork/SumNotPRimeNum.java

Assignment20_AkankshaVyas_New_updatedasperHarsh

---

src/akankshaVyas/Arraypkg/NoDigtNoUpperCase.java
src/akankshaVyas/Arraypkg/StringWord.java
src/akankshaVyas/Arraypkg/UpperCase.java

Assignemnt23_AkankshaVyas

---

src/swapnilMaheshwari/Assignment21/SecondLargestNumInArray.java
src/swapnilMaheshwari/Assignment21/SecondLargestNumOptimization.java

Assignement21_Swapnil

---

src/smitaVetal/Assignment24.java

Assignment24_Smita

---

src/hindaviIngle/Assignment23_DisplayWordWithDigit.java
src/hindaviIngle/Assignment23_DisplayWordWithNoDigitNoUpper.java
src/hindaviIngle/Assignment23_ReturnMaximumUppercase.java
src/hindaviIngle/Assignment23_getMaxlengthWord.java

Assignment_23_Hindavi

---

src/swapnilMaheshwari/Assignment24/ReplaceElementOfSumOfOtherElements.java

Assignment24_SwapnilM

---

src/komalShrivastava/RepeatedWords.java

Assignment - 25 :
Program to print all the repeated or non repeated word in given string.

Assignment25_Komal

---

src/adittyThakare/stringoperations/Assignment25_Program1.java
src/adittyThakare/stringoperations/Assignment25_Program2.java

Assignment 25 Program1:
Assignment 25 Program2:

Assignment25_Aditty

---

src/maheshSantoki/LoopExamples/CharacaterFrequency.java

Assignment_26_MaheshS

---

src/hindaviIngle/Assignment26.java

Assignment_26_Hindavi

---

src/sanket/ArrayOperationsEx7.java

Assignment26_Sanket

---

src/apurvaBabel/Assignment26.java

Assignment26_ApurvaB

---

src/adittyThakare/stringoperations/Assignment26.java

Assignment26_Aditty

---

src/pujaSah/assignments20_30/CountDigitsInString.java
src/pujaSah/assignments20_30/FrequencyOfLettersInString.java
src/pujaSah/assignments20_30/OperationsOnArray.java
src/pujaSah/assignments20_30/OperationsOnStringClassMethods.java
src/pujaSah/assignments20_30/RepeatedWordsInfo.java
src/pujaSah/assignments20_30/StringMethods.java
src/pujaSah/assignments20_30/SumOfDigitsOfEachStringInAnArray.java
src/pujaSah/assignments20_30/middleCharOfMaxLengthString.java

Please Review Assignment25

---

src/asthaSrivastava/array/split/RepeatedWords.java

Assignment25_Astha

---

src/swapnilMaheshwari/StringPrograms/Assignment25/NonRepetatedWord.java
src/swapnilMaheshwari/StringPrograms/Assignment25/RepeatedWord.java

Duplicate word - 
Not repeated word -

Assignment25_SwapnilM

---

src/nehaniG/Assignment25.java

Assignment25_Nehanig

---

src/apurvaBabel/Assignment25.java

Assignment25_ApurvaB

---

src/hindaviIngle/Assignment25.java

Assignment_25_Hindavi

---

src/shubhamG/Assignment21to30/Assignment26.java

Assignment26_Shubham

---

src/pujaSah/assignments20_30/FrequencyOfLetterInString.java

Assignment26 puja sah 21 sep

---

src/manjiri/arrayEx/ArrayEx14.java

Assignment25-Manjiri

---

src/priyankaD/arrayType/GetSumOfArray.java
src/priyankaD/arrayType/MiddleLetterInStringArray.java
src/priyankaD/arrayType/MinAndMaxNumberInString.java
src/priyankaD/stringType/GetDigitsInOrder.java
src/priyankaD/stringType/GetFrequencyOfLetter.java
src/priyankaD/stringType/GetStringInOrder.java
src/priyankaD/stringType/LengthOfName.java
src/priyankaD/stringType/MiddleChar.java
src/priyankaD/stringType/ReverseOrderName.java

Assignment_16_to_19_Priyanka

---

src/asthaSrivastava/assignments/FrequencyOfChar.java

Assignment26_Astha

---

src/shivaniLikhia/MiddleCharFromArray.java

Program 2 from Test3_ShivaniL

---

src/jagruti/Assignment20/CountOfVowels.java
src/jagruti/Assignment20/CountVowelsFromArray.java
src/jagruti/Assignment20/DiffBetweenEvenAndOddNumbers.java
src/jagruti/Assignment20/ReturnMaximumLengthName.java
src/jagruti/Assignment20/SumOfEvenNumbersArray.java
src/jagruti/Assignment20/SumOfNonPrimeNumbersDivBy5and7.java
src/jagruti/Assignment20/SumOfNotPrimeNumbers.java

Assignment20_Jagruti

---

src/shivaniLikhia/MaxLengthWordFromString.java
src/shivaniLikhia/WordWithMaxUpperCase.java
src/shivaniLikhia/WordWithNoDigitNoUppercase.java
src/shivaniLikhia/WordsWithAtleastOneDigit.java

Assignment23_ShivaniL

---

src/hemanshi/Assignment_26.java

Assignment_26

---

src/smitaVetal/Assignment26.java

Assignment26_Smita_Modified

---

src/swatiM/assignment/arrayPrograms/ReplaceElementWithSumOfOtherElements.java
src/technocredits/inheritance/Child1.java
src/technocredits/inheritance/Employee.java
src/technocredits/inheritance/Manager.java
src/technocredits/inheritance/p1/A.java
src/technocredits/inheritance/p2/B.java
src/technocredits/inheritance/p2/C.java
src/technocredits/inteview/Client.java
src/technocredits/inteview/Interview1.java
src/technocredits/inteview/SingleMethod.java
src/technocredits/inteview/Test.java
src/technocredits/inteview/Test4.java
src/technocredits/polymorphismdemo/p1/A.java
src/technocredits/polymorphismdemo/p1/B.java
src/technocredits/polymorphismdemo/p1/C.java
src/technocredits/polymorphismdemo/p1/Parent.java
src/technocredits/polymorphismdemo/p2/Child.java

Assignment24 swati

---

src/swatiM/assignment/arrayPrograms/RepeateNonRepeateWords.java
src/swatiM/assignment/arrayPrograms/ReplaceElementWithSumOfOtherElements.java
src/technocredits/inheritance/Child1.java
src/technocredits/inheritance/Employee.java
src/technocredits/inheritance/Manager.java
src/technocredits/inheritance/p1/A.java
src/technocredits/inheritance/p2/B.java
src/technocredits/inheritance/p2/C.java
src/technocredits/inteview/Client.java
src/technocredits/inteview/Interview1.java
src/technocredits/inteview/SingleMethod.java
src/technocredits/inteview/Test.java
src/technocredits/inteview/Test4.java
src/technocredits/polymorphismdemo/p1/A.java
src/technocredits/polymorphismdemo/p1/B.java
src/technocredits/polymorphismdemo/p1/C.java
src/technocredits/polymorphismdemo/p1/Parent.java
src/technocredits/polymorphismdemo/p2/Child.java

Assignment25 swati

---

src/saroj/arrayPrograms/Assignment25.java

Assignment25 saroj

---

src/vibhaS/Assignment/Assignment27.java

Assignment27_vibha

---

src/manjiri/assignments/assignment27printuniquecharacter/FirstUniqueCharString.java
src/manjiri/assignments/assignment27printuniquecharacter/UniqueCharString.java

UniqueCharString.java
FirstUniqueCharString.java

Assignment27-Manjiri

---

src/hindaviIngle/Assignment27.java

Assignment_27_Hindavi

---

src/hardikBhatia/Assignments/Assignment25.java

Assignment25_Hardik

---

src/nilamP/StringOperations5.java

Assignment26_Nilam

---

src/gauravSahu/Assignment27A.java
src/gauravSahu/Assignment27B.java

Assignment_27_A & B

---

src/rahulSaswadkar/arrayPrograms/ArrayProgram10.java

Assignment26_Rahul

---

src/rahulSaswadkar/arrayPrograms/ArrayProgram5.java
src/rahulSaswadkar/arrayPrograms/ArrayProgram7.java
src/rahulSaswadkar/arrayPrograms/ArrayProgram8.java
src/rahulSaswadkar/arrayPrograms/ArrayProgram9.java

Assignment25_Rahul

---

src/titikshaG/Reversestringatoddindex.java

//Program 1: Print all the repeated word in given string.
//String str = "Maulik Puja Hindavi Shubham Hindavi Shubham Titiksha Swati";
//output : Hindavi 
//Shubham 
public class Repeatwords
{
void repeatWordsFromArray(String name)
{ 
name=name.toLowerCase();
String arr[]=name.split(" ");
int count;
for(int index=0;index<arr.length;index++)
{
count=1;
for (int j=index+1;j<arr.length;j++)
{
if(arr[index].equals(arr[j]))
{
count++;
arr[j]=" ";
}}
if(count>1 && arr[index]!=" ")
System.out.println(arr[index]);
}}
//Program 2: Print all the non repeated word in given string.
//String str = "Maulik Puja Hindavi Shubham hindavi Shubham Titiksha Swati";
//output : Maulik 
//Puja
//Titiksha
//Swati
void nonRepeatWordsFromArray(String name)
{ 
String nonRepeat=" ";
String …

Assignmnet_25_Titiksha

---

src/shridharKumbhar/Assignment11_20/Assignment22.java

Assignment 22 Shridhar

---

src/shivaniLikhia/Assignment20.java

src/shivaniLikhia/Assignment20.java

Assignment20_ShivaniL

---

src/shridharKumbhar/assignment21_30/Assignment21.java

Assignment 21 and Package : assignment21_30

---

src/pranjaliV/assignment18/StringAssignment2.java
src/pranjaliV/assignment22/Assignment22.java

Assignment 22 pranjali

---

src/komalShrivastava/UniqueCharacter.java

Assignment-27 : 23rd Sep'2022
Program to print unique character and 1st unique character of each name in given string array.
String[] arrName = {"MaulikM", "KananiK","Mahesh", "AakankshA"};

Assignment27_Komal

---

src/adittyThakare/stringoperations/Assignment27_Program1.java
src/adittyThakare/stringoperations/Assignment27_Program2.java

Assignment27_Aditty

---

src/anujaD/ArrayExample.java
src/anujaD/StringProgram.java

Assignment19 anuja

---

src/akankshaVyas/StringOperation/Assingnment26EachCharFreqString.java
src/akankshaVyas/StringOperation/StringFormatting.java

C:/Program Files/Git/Assingnment26EachC

---

src/titikshaG/Countofvowels.java

import java.util.Arrays;
//Program 1 : [10 mins - 13 mins]
//Return count of vowels in a given String using switch case.
public class Countofvowels {
int totalNumberOfVowels(String name){
int count=0;
name=name.toLowerCase();{
for(int index=0;index<name.length();index++){
char ch=name.charAt(index);
switch (ch) {
case 'a': 
case 'e':
case 'i': 
case 'o': 
case 'u': 
count++;}
}
}
return count;}
//Program 2 : [10 mins]
//Return first vowel from given String
char firstVowel(String name){
name=name.toLowerCase();
char ch=name.charAt(0);
int count=0;
for(int index=0;index<name.length();index++){
ch=name.charAt(index);{
switch (ch) {
case 'a': 
case 'e':
case 'i': 
case 'o': 
case 'u': 
count++;
break;}
}
if(count==1)
break;}
return ch ;}
//Program 3:Print count of each …

Assignmnet_28_Titiksha

---

src/deepakBorse/Assignments/Assignment27.java

Assignment_DeepakB

---

src/nehaniG/Assignment27.java

Assignment27_Nehanig

---

src/jagruti/Assignment22new/Assignment22new.java

Assignment22new

---

src/hindaviIngle/Assignment28.java
src/hindaviIngle/Assignment29.java

Assignment 29 hindavi

---

src/deepakBorse/Assignments/Assignment28.java

Assignment28_DeepakB

---

src/nehaniG/Assignment29.java

Assignment29_Nehanig

---

src/jagruti/Assignment21/ReturnSecondHighestFromArray.java

Assignment21

---

src/deepakPatil/Assignment26StringReplaceMethod/Assignment26.java
src/technocredits/basicexamples/DoWhileExample.java
src/technocredits/basicexamples/SwitchExample1.java
src/technocredits/basicexamples/WhileLoopExample.java
src/technocredits/construtordemo/A.java
src/technocredits/construtordemo/B.java
src/technocredits/construtordemo/Example.java
src/technocredits/construtordemo/Student.java
src/technocredits/inheritance/p1/Employee.java
src/technocredits/inheritance/p1/Mananger.java
src/technocredits/inheritance/p1/Parent.java
src/technocredits/inheritance/p2/Child.java
src/technocredits/inteview/EnhanceLoopExample.java

Assignment26 deepak p

---

src/swapnilMaheshwari/ArrayPrograms/ShiftAllZerosAtTheEnd.java
src/swapnilMaheshwari/ArrayPrograms/ShiftAllZerosAtTheFirstIndex.java

Shift all zeros at the end of array list -
Shift all zeros at the first index of array list-

Assignment29_SwapnilM

---

src/chaitanyaMankar/Array/MvePosition.java
src/chaitanyaMankar/String/StringFunct.java
src/chaitanyaMankar/SwitchCase/SwtchCse.java

Assignment29

---

src/swatiM/assignment/arrayPrograms/ShiftZeroAtEnd.java
src/swatiM/assignment/arrayPrograms/ShiftZeroAtStart.java

Assignment29_Swati

---

src/deepakBorse/Assignments/Assignment29.java
src/deepakBorse/Practice/Testdemo2.java

Assignment29 deepak b

---

src/priyankaD/assignments_20_30/Assignment_23_1_2.java
src/priyankaD/assignments_20_30/Assignment_23_3_4.java
src/priyankaD/assignments_20_30/Assignment_24.java

Assignments_23_24_priyanka

---

src/vibhaS/Assignment/Assignment30.java

Assignment30_vibha

---

src/deepakBorse/Abstraction/Interfaceexample.java
src/deepakBorse/Abstraction/Interfaceimplements.java
src/deepakBorse/Abstraction/TestBank.java
src/deepakBorse/Abstraction/package-info.java
src/deepakBorse/Assignments/Assignment30.java

Assignment30_DeepakB

---

src/manjiri/arrayEx/assignment30/SearchDuplicateNumbers.java

Assignment30-Manjiri

---

src/adittyThakare/arrayoperations/Assignment30.java

Assignment30_Aditty

---

src/hindaviIngle/Assignment22.java
src/hindaviIngle/Assignment30.java

Assignment 30 hindavi

---

src/kiran/assignment30/DuplicateElementInArray.java
src/kiran/assignmet29/ArrayShiftZero.java

Assignment30_kiran

---

src/shubhamG/Assignment21to30/Assignment30DuplicateNumberArray.java

Assignment30_Shubham

---

src/pujaSah/assignments20_30/DuplicateNumbers.java

Please Review assignment 30

---

src/maheshSantoki/arrayExamples/DuplicateNumber.java

Assignment30_MaheshS

---

src/nehaniG/Assignment30.java

Assignment30_Nehanig

---

src/harshalRane/Assignments/assignment30/Assignment30.java

Assignment30_Harshal

---

src/sagarY/Assignment30/FindDuplicateNumsFromArray.java

Assignment30_sagarY

---

src/akankshaVyas/Arraypkg/ArrayNum.java

Assignemnet29_AkankshaVyas

---

src/asthaSrivastava/assignments/UniqueChar.java

Assignment27_Astha

---

src/asthaSrivastava/array/assignments/ShiftZeros.java

Assignment29_Astha

---

src/pranjaliV/assignment25/ArrayEx25.java

Assignment_25_Pranjali

---

src/swapnilMaheshwari/ArrayPrograms/DuplicateNumbersFromArray.java

Assignment30_SwapnilM

---

src/shrutiArora/Assignment31.java
src/shrutiArora/Assignment32.java

Assignment32_33_shruti

---

src/sanket/ArrayDuplicateNum.java

Assignment30_Sanket

---

src/asthaSrivastava/arrayBasics/MaxLengthName.java

Updated code by removing extra blank line. Please review

Assignment23_Astha

---

src/apurvaBabel/Assignment30_DuplicateNumbers.java

Assignment30_ApurvaB

---

src/adittyThakare/stringoperations/Assignment31_Program1.java
src/adittyThakare/stringoperations/Assignment31_Program2.java

Assignment 31 Program1:
Assignment 31 Program2:

Assignment31_Aditty

---

src/komalShrivastava/ArrayIntegerDuplicate.java

Assignment - 30 : 28th Sep'2022
Program to find duplicate and unique numbers from given array.

Assignment30_Komal

---

src/asthaSrivastava/assignments/DuplicateNumbers28Sept.java

Assignment30_Astha

---

src/deepakPatil/Assignment27EnhanceForIndexOf/Assignment27.java

Assignment27_DeepakP

---

src/saroj/arrayPrograms/Assignment29.java

Assignment 29 Saroj

---

src/saroj/switchcaseProgram/Assignment28.java

Assignment28 Saroj

---

src/rashmiG/ArrayAssignments/ShiftZerosAtBeginningOfArray.java
src/rashmiG/ArrayAssignments/ShiftZerosAtEndOfArray.java

Assignment29_RashmiG

---

src/sagarY/Assignment_31/PalindromeArrayCheck.java
src/sagarY/Assignment_31/PalindromeArrayCheckByStringReverse.java
src/sagarY/Assignment_31/PalindromeByStringReverse.java
src/sagarY/Assignment_31/PalindromeCheck.java

Assignment31_sagarY

---

src/pranjaliV/assignment31/Palindrome31.java

Assignment_31_Pranjali

---

src/maheshSantoki/SpecialInterview/Palindrome.java

Assignment3_MaheshS

---

src/rashmiG/palindromeAssignements/PalindromeArray.java
src/rashmiG/palindromeAssignements/PalindromeString.java

Assignment31_RashmiG

---

src/titikshaG/ZeroIndex.java

//Assignment-29
//Program 1 : 
//Shift all Zero's at the end of an array.
//input : {10,0,0,3,4,5,0,9}
//output : {10,3,4,5,9,0,0,0}
import java.util.Arrays;
public class ZeroIndex {
void arrangingZeroInLastIndexs(int[] arr) {
int[] output=new int[arr.length];
int count=0;
for(int index=0;index<arr.length;index++) {
if(arr[index]==0){
count++;}
}
for(int index=0;index<arr.length;index++) {
if(arr[index]!=0){
output[count]=arr[index];
count++;}
}
System.out.println("The output array is :"+Arrays.toString(output));
}
//Program 2 : 
//Shift all Zero's at the end of an array.
//input : {10,0,0,3,4,5,0,9}
//output : {0,0,0,10,3,4,5,9}
void arrangingZeroInFirstIndexs(int[] arr) {
int[] output=new int[arr.length];
int count=0;
for(int index=0;index<arr.length;index++) { …

Assignmnet_29_Titiksha

---

src/akankshaVyas/Arraypkg/Assignment30_ArrayDupNum.java

Assignment30_AkankshaVyas

---

src/saroj/arrayPrograms/Assignment30.java

Assignment30 Saroj

---

src/pujaSah/assignments31_40/PallindromExample.java

Please review Assignment 31

---

src/hemanshi/Assignment_28.java

Assignment_28

---

src/vibhaS/Assignment/Assignment31.java

Assignment31_vibha

---

src/manjiri/StringEx/assignment31/CheckPallindormString.java
src/manjiri/StringEx/assignment31/CheckPallindromFromArray.java
src/manjiri/StringEx/assignment31/CheckPallindromWithoutReversingString.java

CheckPallindrom.java
CheckPallindromWithoutStringReverse.java
CheckPallindromFromArray.java

Assignment31-Manjiri

---

src/hemanshi/Assignment_27.java

Assignment_27

---

src/akankshaVyas/ArrayWork/Assignment25DuplicateWordString.java

Assignment25_AkankshaVyas

---

src/kiran/Assignment31/PalindromString/PalindromString.java

Assignment31_kiran

---

src/kiran/assignment26/FrequencyOfCharInString/FrequencyOfChar.java

Assignment26_kiran

---

src/shubhamG/Assignment31to40/Assignment31Pallindrome.java

Assignment31_Shubham

---

src/apurvaBabel/Assignment31_PallindromeWords.java

Assignment31_ApurvaB

---

src/shivaniLikhia/Assignment30.java

Assignment30_ShivaniL

---

src/asthaSrivastava/string/Pallindrom.java

Assignment31_Astha

---

src/shraddhaRekhate/Asignment31/ArrayPallindrome.java
src/shraddhaRekhate/Asignment31/Pallindrome.java

string pallindrome
array pallindrome

Assignment31_ShraddhaR

---

src/pranjaliV/assignment30/ArrayEx30.java

Assignment_30_Pranjali

---

src/rashmiG/Numberprograms/ArmStrongNumber.java
src/rashmiG/Numberprograms/PalindromeNumber.java
src/rashmiG/Numberprograms/ReverseNumber.java

Program 1:
Program2:
Program 3:

Assignment32_RashmiG

---

src/pranjaliV/assignment32/ArrayEx32.java

Assignment_32_Pranjali

---

src/nikitaPhase/Armstrong.java
src/nikitaPhase/Palindrome.java
src/nikitaPhase/ReverseNum.java

[Assignment_32_Armstrong](https://drive.google.com/file/d/1G1Ie9wfXTfmKeLtbxeBxmnRIQKD39BWo/view?usp=sharing)
[Assignment_32_Palindrome](https://drive.google.com/file/d/1VJA_L63WocLiY6t8n01Bjo__qgsmn3YJ/view?usp=sharing)
[Assignment_32_ReverseNum](https://drive.google.com/file/d/1NjBQKXFz5m2clDZPQRGidBDAtx0l0BKj/view?usp=sharing)

Assignment_32_NikitaP

---

src/sagarY/Assignment_32/ArmstrongNum.java
src/sagarY/Assignment_32/PalindromNumber.java
src/sagarY/Assignment_32/ReverseNum.java

Assignment32_sagarY

---

src/hemanshi/Assignment_31.java

Assignment_31

---

src/sanket/NumbersPrograms.java

Assignment32_Sanket

---

src/shubhamG/Assignment21to30/Assignment32ArmstrongNumber.java
src/shubhamG/Assignment21to30/Assignment32PallindromeNumber.java
src/shubhamG/Assignment21to30/Assignment32ReverseNumber.java

Assignment32_Shubham

---

src/vibhaS/Assignment/Assignment32.java

Assignment32_vibha

---

src/saroj/Assignment32.java

Assignment32--Saroj

---

src/shivaniLikhia/Assignment32.java

Assignment32_ShivaniL

---

src/harshalRane/Assignments/assignment31/Assignment31.java

Assignment31_Harshal

---

src/gauravSahu/Assignment31.java
src/gauravSahu/Assignment31A.java
src/gauravSahu/Assignment32A.java
src/gauravSahu/Assignment32B.java
src/gauravSahu/Assignment32C.java

Assignment31&32

---

src/apurvaBabel/Assignment33_DuplicateUniqueNames.java
src/apurvaBabel/Assignment33_DuplicateUniqueNumbers.java
src/apurvaBabel/Assignment33_FrequencyOfNumbers.java
src/apurvaBabel/Assignment33_MissingNumbers.java

Program 1 ,Program 2 ,Program 6
Program 4 ,Program 5
Program 3
Program7

Assignment33_ApurvaB

---

src/akankshaVyas/Arraypkg/NumOperation.java

Assignment32_akankshaVyas

---

src/hardikBhatia/Assignments/Assignment33.java

Assignment33_Hardik

---

src/nilamP/ArrayOperations5.java

assignment31_Nilam

---

src/maheshSantoki/SpecialInterview/ArmstrongNumber.java
src/maheshSantoki/SpecialInterview/PallindromeNumber.java
src/maheshSantoki/SpecialInterview/ReverseNumber.java

Assignment32_MaheshS

---

src/deepakBorse/Assignments/Assignment32.java
src/deepakBorse/Assignments/Palendrome.java

commited two files - Assignment32 completed. Assignment31 with other way

Assignment32_DeepakB

---

src/sagarY/Assignment_33/PrintDuplicateNames.java
src/sagarY/Assignment_33/PrintDuplicateNum.java
src/sagarY/Assignment_33/PrintEachNumberFreq.java
src/sagarY/Assignment_33/PrintMissingNumber.java
src/sagarY/Assignment_33/PrintMissingNumbers.java
src/sagarY/Assignment_33/PrintUniqueNames.java
src/sagarY/Assignment_33/PrintUniqueNum.java
src/sagarY/Assignment_33/PrintUniqueNumbers.java

Assignment33_sagarY

---

src/harshalRane/Assignments/assignment32/ArmstrongNumber.java
src/harshalRane/Assignments/assignment32/Pallindrome.java
src/harshalRane/Assignments/assignment32/ReverseNumber.java

Program 1: Armstrong Number
Program 2: Reverse Number
Program 3: Pallindrome

Assignment32_Harshal

---

src/akankshaVyas/basicExamples/SwitchCase.java

Assignment28_AkankshaVyas

---

src/pujaSah/assignments31_40/PallindromNumbers.java

Assignment32 puja sah 30 sep

---

src/asthaSrivastava/armstrong/FindArmstrongNum.java
src/asthaSrivastava/armstrong/PallindromeNumber.java
src/asthaSrivastava/armstrong/ReverseNum.java

Assignment32_Astha

---

src/chaitanyaMankar/Array/PallindromeArray.java
src/chaitanyaMankar/String/Palindrome.java

Assignment31 Palindrome 2 Prgm

---

src/nikeshM/ArrayProgram/DifferenceOfSum.java
src/nikeshM/ArrayProgram/MaximumLength.java
src/nikeshM/ArrayProgram/PrintSecondHighestNo.java
src/nikeshM/ArrayProgram/ReplaceCurrentNo.java
src/nikeshM/ArrayProgram/SumOfGivenArrey.java
src/nikeshM/ArrayProgram/SumOfNonPrime.java
src/nikeshM/ArrayProgram/SumOfNonPrimeNumber.java
src/nikeshM/ArrayProgram/Test3Program1.java
src/nikeshM/ArrayProgram/Test3Program2.java
src/nikeshM/ArrayProgram/countOfVowles.java

Assignment _20 to 22_Nikesh

---

src/chaitanyaMankar/Array/DuplicateNumber.java
src/chaitanyaMankar/Array/DuplicateNumberSearch.java

Assignment30 chaitanya m

---

src/swatiM/assignment/Assignment30_DuplicateNumbers.java
src/swatiM/assignment/Assignment31_ArrayPallindrome.java
src/swatiM/assignment/Assignment31_StringPallindrome.java
src/swatiM/assignment/Assignment32.java

Assignment32 swati

---

src/swatiM/assignment/Assignment30_DuplicateNumbers.java

Assignment30_Swati

---

src/adittyThakare/numberOperations/Assignment32_Program1.java
src/adittyThakare/numberOperations/Assignment32_Program2.java
src/adittyThakare/numberOperations/Assignment32_Program3.java

Assignment 32 Program1:
Program 2:
Program 3:

Assignment32_Aditty

---

src/komalShrivastava/DuplicateUniqueNumbers.java

Program 1: print duplicate numbers from given array. 
Program 2 : print unique numbers from given array (having freq 1). 
program 3 : print missing numbers from given array from range 1 to 10. 
program 4: print duplicate names from given array (do not consider case sensitivity). 
program 5 : print unique names from given array. 
Program 6 : print unique numbers from given array (all content uniquely). 
program 7 : print each number with its frequency.

Assignment33_Komal

---

src/sagarY/Assignment_34/FibonacciSeries.java
src/sagarY/Assignment_34/FindFactorial.java
src/sagarY/Assignment_34/IsAnagram.java

Program 1:
Program 2:
Program 3:

Assignment34_sagarY

---

src/apurvaBabel/Assignment34_AnagramString.java
src/apurvaBabel/Assignment34_Factorial.java
src/apurvaBabel/Assignment34_FibonacciSeries.java

Assignment34_ApurvaB

---

src/harshalRane/Assignments/assignment34/AnagramString.java
src/harshalRane/Assignments/assignment34/Factorial.java
src/harshalRane/Assignments/assignment34/Fibonacci.java

Program 1:
Program 2:
Program 3:

Assignment34_Harshal

---

src/nilamP/ArrayOperations4.java

assignment32_Nilam

---

src/sanket/Assignment34AnagramStrings.java
src/sanket/Assignment34FactorialFibonacci.java

Anagram String Results:
Factorial and Fibonacci Series:

Assignment34_Sanket

---

src/rahulSaswadkar/arrayPrograms/ArrayProgram13.java

Assignment30_Rahul

---

src/rahulSaswadkar/arrayPrograms/Shift0InArray.java

Assignment29_Rahul

---

src/rahulSaswadkar/arrayPrograms/ArrayProgram12.java

Assignment28_Rahul

---

src/akankshaVyas/Arraypkg/Assignement33.java

Assignement33_AkankshaVyas

---

src/harshalRane/Assignments/assignment33/AllUniqueNumbersArray.java
src/harshalRane/Assignments/assignment33/DuplicateNamesArray.java
src/harshalRane/Assignments/assignment33/DuplicateNumbersArray.java
src/harshalRane/Assignments/assignment33/FrequencyEachNumberArray.java
src/harshalRane/Assignments/assignment33/MissingNumbersArray.java
src/harshalRane/Assignments/assignment33/UniqueNameArray.java
src/harshalRane/Assignments/assignment33/UniqueNumberArray.java

Program 1:
Program 2:
Program 3:
Program 4:
Program 5:
Program 6:
Program 7:

Assignment33_Harshal

---

src/pujaSah/assignments20_30/ArrayAndString.java

Assignment33_PujaSah_01Oct

---

src/sanket/ProgramOnStringNumbers.java

Assignment33_Sanket

---

src/deepakPatil/Assignment29ShiftZeroArrayExample/Assignment29.java

Assignment29_DeepakP

---

src/deepakPatil/Assignment28SwitchCase/Assignment28_1.java
src/deepakPatil/Assignment28SwitchCase/Assignment28_2.java

Assignment28_DeepakP

---

src/komalShrivastava/ArmstrongReversePalindrome.java

Program to check if input number is Armstrong or Palindrome and find Reverse of the input number

Assignment32_Komal

---

src/nilamP/ArrayOperations4.java

assignment33_Nilam

---

src/titikshaG/Assignmnet_33.java
src/titikshaG/PartB_Assignment_33.java

//Program 1: print duplicate numbers from given array. 
//input : {10,20,10,44,33,55,33};
//output : 10
// 33
public class Assignmnet_33{ 
void getduplicateNumber(int[] arr) {
for(int index=0;index<arr.length;index++) {
for(int innerLoop=index+1;innerLoop<arr.length;innerLoop++) {
if(arr[index]==(arr[innerLoop])) {
System.out.println("The duplicate values are:"+" "+arr[index]); }
}
}
}
//Second method to find duplicate number by replacing non-duplicate numbers with zero
int getsecondMethofToFindZeoValue(int[] num) {//finding zeros in array
int count=0;
for(int index=0;index<num.length;index++){
if(num[index]==0) {
count++;}
}
return count;
}
void getsecondMethofToFindDuplicate(int[] number) {
int countOfZero=getsecondMethofToFindZeoValue(number);
if(countOfZero==0); …

Assignment_33_Titiksha

---

src/namratamishra/Basic_Operations/DayBasedonDayIndex.java
src/namratamishra/Basic_Operations/QuarterBasedonIndex.java
src/namratamishra/Basic_Operations/WeekdayorWeekendsBasedonDayIndex.java

namratamishra_assignment_4 using scanner class

---

src/namratamishra/Basic_Operations/ScoreGradeResults.java
src/namratamishra/Basic_Operations/Studentinfo.java

namratamishra_assignment_5

---

src/namratamishra/Basic_Operations/PrimeNumber.java

namratamishra_assignment_8and9_using_scanner_class

---

src/deepakBorse/Assignments/Assignment35.java
src/deepakBorse/Assignments/Primenumberinter.java

Assignment35_DeepakB

---

src/namratamishra/stringOpreations/StringRearrange.java
src/namratamishra/stringOpreations/StringRearrangeDigitUpperLower.java
src/namratamishra/stringOpreations/StringTargetCharFrequency.java

namratamishra_assignment_18_using_UserInput

---

src/namratamishra/Array/ArrayMaxNumber.java
src/namratamishra/Array/ArrayMiddleChar.java
src/namratamishra/Array/ArrayMinNumber.java
src/namratamishra/Array/ArraySumOfNumbers.java
src/namratamishra/Array/ArraySumOfPrimeNumber.java

namratamishra_assignment_19

---

src/namratamishra/Array/ArrayCountofVowels.java
src/namratamishra/Array/ArrayDiffofSumofEvenOdd.java
src/namratamishra/Array/ArrayNameMaxLength.java
src/namratamishra/Array/ArraySumOfNotPrimeNumber.java
src/namratamishra/Array/ArraySumOfNotPrimeNumberandDivby5and7.java
src/namratamishra/Array/ArraySumofEvenNumber.java
src/namratamishra/Array/StringCountofVowels.java

namratammishra_assignment_20

---

src/pankajBhatt/Assignment22_15Sep2022.java

Pankaj_Assignment_22_15Sep2022

---

src/namratamishra/assignment31/PalendromeString.java
src/namratamishra/assignment31/PalendromeStringMultpleCheck.java

namrtamishra_assignment_31

---

src/sohail/array/ReplaceArrayIndex.java

Assignment_22_Sohail

---

src/namratamishra/Array/ArrayDuplicateNumberCount.java

namratamishra_assignment_30

---

src/namratamishra/Array/ArrayElementsReplacingWithSumofOtherElements.java

namratamishra_assignment_24

---

src/namratamishra/Array/ArrayRepalcingElements.java

namratamishra_assignment_22

---

src/namratamishra/Basic_Operations/PrimeNumberCountSumAvginGivenRange.java

namratamishra_assignment_12

---

src/namratamishra/Basic_Operations/Last3NumDivby3and7.java

namratamishra_assignment_10

---

src/nehaniG/Assignment23.java
src/nehaniG/Assignment25.java
src/nehaniG/Assignment26.java
src/nehaniG/Assignment27.java
src/nehaniG/Assignment28.java
src/nehaniG/Assignment29.java
src/nehaniG/Assignment30.java
src/nehaniG/Assignment31.java
src/nehaniG/Assignment32.java
src/nehaniG/Assignment34.java
src/nehaniG/Assignment36.java

Added missing files and completed Assignment 36

---

src/sohail/array/SecondHighest.java

Assignment_21_Sohail

---

src/sohail/stringprograms/SumOfDigitInArray.java

Test_4_Sohail

---

src/pankajBhatt/Assignment26_21Sep2022.java

Pankaj_Assignment26_21Sep2022

---

src/titikshaG/Anagramprogram.java
src/titikshaG/FactorialAndFabinacciSeries.java

//Program 1 : How to check if two given String is the anagram of each other (using scanner class)?
//Input1: catc
//Input2: actc
//Output: anagram
import java.util.Arrays;
import java.util.Scanner;
public class Anagramprogram {
//Method 1-Using sort method
public static boolean isAnagram(String str1,String str2) {
char[] arr1=str1.toCharArray();
char[] arr2=str2.toCharArray();
Arrays.sort(arr1);
Arrays.sort(arr2);
for(int index=0;index<arr1.length;index++) {
if(arr1[index]!=arr2[index])
return false;}
return true;
}
//Method 2-using replace method
public static void isAnagram2(String str1,String str2) {
if(str1.length() !=str2.length()){
System.out.println("Not a anagram");}
else {
while(str1.length()>0) {
char ch=str1.charAt(0); …

Assignment_34_Titiksha

---

src/pankajBhatt/Assignment25_P1_20Sep2022.java

Pankaj_Assignment25_20Sep2022

---

src/pankajBhatt/Assignment24_17Sep2022.java

Pankaj_Assignment24_17Sep2022

---

src/gauravSahu/Array20Test2.java
src/gauravSahu/Assignment36A.java
src/gauravSahu/Assignment36D.java
src/gauravSahu/Assignment36E.java
src/gauravSahu/Assignment36G.java
src/gauravSahu/Practice/Practice1.java
src/gauravSahu/Practice/Practice2.java
src/gauravSahu/Practice/Practice3.java
src/gauravSahu/Practice/Practiceanagram.java
src/gauravSahu/Practice/Practiceanagram2.java
src/gauravSahu/ScannerArray.java
src/gauravSahu/String/StringMethods.java
src/gauravSahu/assignments/Assignement23.java
src/gauravSahu/assignments/Assignment21.java
src/gauravSahu/assignments/Assignment23B.java
src/gauravSahu/assignments/Assignment23C.java
src/gauravSahu/assignments/Assignment23D.java
src/gauravSahu/assignments/Assignment24.java
src/gauravSahu/assignments/Assignment25.java
src/gauravSahu/assignments/Assignment25B.java
src/gauravSahu/assignments/Assignment26.java
src/gauravSahu/assignments/Assignment29A.java
src/gauravSahu/assignments/Assignment29B.java
src/gauravSahu/assignments/String18Assign.java
src/gauravSahu/collections/ArrayList.java
src/gauravSahu/exception/A.java
src/gauravSahu/exception/B.java
src/gauravSahu/exception/C.java

Assignment gaurav 36

---

src/hemanshi/Assignment_35.java

Assignment_35

---

src/priyankaD/assignments_20_30/Assignment_28.java
src/priyankaD/assignments_20_30/Assignment_29.java
src/priyankaD/assignments_20_30/Assignment_30.java

Assignment_28_priyanka

---

src/shraddhaRekhate/Assignment20/COuntVowelsOfEachNameInGIvenArray.java
src/shraddhaRekhate/Assignment20/CountOfVowelsInString.java
src/shraddhaRekhate/Assignment20/DiffSumEvenandOdd.java
src/shraddhaRekhate/Assignment20/NameHavingMaximunLength.java
src/shraddhaRekhate/Assignment20/SumOfAllEvenNo.java
src/shraddhaRekhate/Assignment20/SumOfNonPNoDIvBy5and7.java
src/shraddhaRekhate/Assignment20/SumOfNonPrimeNumber.java

Assignment20_ShraddhaR

---

src/nikeshM/Assignment31/Assignment31Program1.java
src/nikeshM/Assignment31/Assignment31Program2.java

Assignment_31_Nikesh

---

src/swatiM/assignments/ascii/Assignment36_Program1.java
src/swatiM/assignments/ascii/Assignment36_Program2.java
src/swatiM/assignments/ascii/Assignment36_Program3.java
src/swatiM/assignments/ascii/Assignment36_Program4.java
src/swatiM/assignments/ascii/Assignment36_Program5.java
src/swatiM/assignments/ascii/Assignment36_Program6.java
src/swatiM/assignments/ascii/Assignment36_Program7.java

Assignment36_Swati

---

src/deepakBorse/Assignments/Assignment36.java

Assignment36_DeepakB

---

src/chaitanyaMankar/Assignment25/Assignment25.java

Assignment25 Added

---

src/namratamishra/logicalPrinting/ArmstrongNumber.java
src/namratamishra/logicalPrinting/PalindromeNum.java
src/namratamishra/logicalPrinting/ReverseNumber.java

namratamishra_assignments_32

---

src/sohail/stringprograms/DigitInString.java
src/sohail/stringprograms/MaxWordOfString.java

Assignment_23_Sohail

---

src/vinod/Assignment/Assignment35.java

Assignment35

---

src/nikitaPhase/Assignment_26_TejasP.java

Assignment_26_TejasP

---

src/sohail/stringprograms/ReplaceSumOfArray.java

Assignment_24_Sohail

---

src/namratamishra/Array/ArrayStringWordsHavingFirstUniqueChar.java
src/namratamishra/Array/ArrayStringWordsHavingUniqueChar.java

namratamishra_assignment_27

---

src/priyankaD/assignments_31_40/Assignment_33.java
src/priyankaD/assignments_31_40/Assignment_34.java

Assignment_33_priyanka

---

src/namratamishra/stringOpreations/findOutFrequencyOfEachCharacter.java

namratamishra_assignment_26

---

src/namratamishra/stringOpreations/ArrayStringNonRepeatedWordsPrint.java
src/namratamishra/stringOpreations/ArrayStringRepeatedWordsPrint.java

namratamishra_assignment_25

---

src/titikshaG/AsciiPrpgram.java

public class AsciiPrpgram {
//Assignment - 36 : 9th Oct'2022
//Program 1 : 
//WAP to return String by encrypting all characters from given string by its next character.
//input : apdz
//output : bqea
String getAsciiNextCharacter(String character) {
String output="";
for(int index=0;index<character.length();index++) {
char ascii=character.charAt(index);
if(ascii == 'z') {
output=output+'a';}
else if (ascii == 'Z') {
output=output+'A';}
else {
output=output+(char)(ascii+1);}
}
return output;
}
//Program 2 : 
//WAP to return ascii of given character.
//input : C
//output : 67
void getAsciiOfGivenChararcter(char ch) {
int ascii=ch;
System.out.println("The ascii of"+" "+ ch +" "+ "is" +" "+ascii);
}
//Program 3 : 
//WAP to print ascii value of A->Z.
//output : A -> 65
// B …

Assignment_36_Titiksha

---

src/namratamishra/Basic_Operations/PrimeNumberUsingWhileLoop.java

namrata_mishra_assignment_14

---

src/shivaniLikhia/Assignment36.java

Assignment36_ShivaniL

---

src/sohail/stringprograms/RepetedWords.java

Assignment_25_Sohail

---

src/apurvaBabel/Assignment31to40/Assignment35.java
src/apurvaBabel/Assignment31to40/Assignment36_Ascii.java
src/apurvaBabel/Assignment31to40/Assignment37_ArrayList.java

Assignment37_ApurvaB

---

src/shubhamG/Assignment1to10/Asignment2Calculator.java
src/shubhamG/Assignment31to40/Assignment37.java

Assignment37_Shubham

---

src/sohail/stringprograms/CountOfRepetedChar.java

Assignment_26_Sohail

---

src/sanket/CollectionArrayList.java

Assignment37_Sanket

---

src/nehaniG/Arraylist/Assignment37.java

Assignment37_Nehanig

---

src/namratamishra/Basic_Operations/FabonaiSeries.java
src/namratamishra/Basic_Operations/Factorial.java
src/namratamishra/stringOpreations/AnagramString.java

namratamishra_assignment_34

---

src/namratamishra/stringOperations/ArrayWordsHavingMaxUpperCase.java
src/namratamishra/stringOperations/StringAllWordsHavingDigit.java
src/namratamishra/stringOperations/StringMaxLengthWord.java

namratamishra_assignment_23

---

src/shraddhaRekhate/Assignment21_26_29_30/Assignment30.java
src/shraddhaRekhate/Assignment21_26_29_30/FrequencyOfChar.java
src/shraddhaRekhate/Assignment21_26_29_30/SecondDhIghestFromArray.java
src/shraddhaRekhate/Assignment21_26_29_30/ShiftAllZero.java

Assignment21_26_29_30_ShraddhaR

---

src/nilamP/CollectionExample.java

assignment37_Nilam

---

src/namratamishra/Array/ArraySecondHighestNumber.java

namratamishra_assignment_21

---

src/sohail/stringprograms/CoutOfEachVowel.java
src/sohail/stringprograms/FirstVowelSwitchCase.java
src/sohail/stringprograms/VowelsSwitchCase.java

Assignment_28_Sohail

---

src/vibhaS/Assignment/Assignment37.java

Assignment37_vibha

---

src/manjiri/assignment36/AsciiOfGivenChar.java
src/manjiri/assignment36/AsciiValueOfCapitalAlphabets.java
src/manjiri/assignment36/CharacterOfGivenAsciiValue.java
src/manjiri/assignment36/CharactersOfGivenAsciiValueRange.java
src/manjiri/assignment36/CountOfDigitsFromString.java
src/manjiri/assignment36/EncryptionExample2.java
src/manjiri/assignment36/StringEncryption.java

StringEncryption.java
AsciiOfGivenChar.java
AsciiValueOfCapitalAlphabets.java
CountOfDigitsFromString.java
CharacterOfGivenAsciiValue.java
CharactersOfGivenAsciiValueRange.java
EncryptionExample2.java

Assignment36-Manjiri

---

src/sohail/stringprograms/UniqueCharacterInString.java

Assignment_27_Sohail

---

src/rashmiG/Collections/ArrayListRemovalOfName.java
src/rashmiG/Collections/ArrayListRemoveAllMultipleOccurences.java
src/rashmiG/Collections/ArrayListRemoveMultipleOccurences.java

Program 1:
Program 2:
Program 3:

Assignment37 rashmi g

---

src/pujaSah/ArrayListAssignments/RemoveAllMultipleOccurance.java
src/pujaSah/ArrayListAssignments/RemoveMultipleOccurance.java
src/pujaSah/ArrayListAssignments/RemoveNameFromList.java

Please review Assignment37

---

src/nikeshM/Assignment32/Assignment32Program1.java
src/nikeshM/Assignment32/PallindrimeNo.java
src/nikeshM/Assignment32/ReverseNo.java

Assignment_32_Nikesh

---

src/shraddhaRekhate/Assignment37/RemovMulOccFromArraList.java
src/shraddhaRekhate/Assignment37/RemoveMultipleOcccuranceArrayList.java
src/shraddhaRekhate/Assignment37/RemoveNameFromArrayList1.java

remove name from array
remove mul occ array
remove mul occ from array

Assignment37_ShraddhaR

---

src/amolMule/ArrCollection.java
src/amolMule/ArrCollection1.java
src/amolMule/ArrCollection2.java
src/amolMule/ArrCollection3.java

Assignment 37 added

---

src/saroj/arrayListPrograms/Assignment37.java

Assignment 37 Saroj

---

src/adittyThakare/collections/Assigment37_Program2.java
src/adittyThakare/collections/Assignment37_Program1.java
src/adittyThakare/collections/Assignment37_Program3.java

Program 1:
Program 2:
Program 3:

Assignment37_Aditty

---

src/deepakPatil/Assignment37ArrayList/Assignment37.java

Assignment37_DeepakP

---

src/anujaD/Assignment28_1.java
src/anujaD/Assignment37.java

Assignment28 anuja

---

src/anujaD/Assignment37.java

Assignment37_Anuja

---

src/manjiri/assignment37/RemoveGivenNameFromArrayList.java
src/manjiri/assignment37/RemoveMultipleOccurance.java
src/manjiri/assignment37/RemoveMultipleOccurancesFromArrayList.java

RemoveGivenNameFromArrayList.java
RemoveMultipleOccurancesFromArrayList.java
RemoveMultipleOccurance.java

Assignment37-Manjiri

---

src/pujaSah/ArrayListAssignments/MarksOfStudents.java
src/pujaSah/ArrayListAssignments/OperationOnStuName.java
src/pujaSah/ArrayListAssignments/OperationsOnArrayList.java
src/pujaSah/ArrayListAssignments/StuName.java

output1:
output2:
output3:
output4:

Please review assignment 38

---

src/smitaVetal/Assignment31_40/Assignment36_1.java
src/smitaVetal/Assignment31_40/Assignment36_2.java
src/smitaVetal/Assignment31_40/Assignment36_3.java
src/smitaVetal/Assignment31_40/Assignment36_4.java
src/smitaVetal/Assignment31_40/Assignment36_5.java
src/smitaVetal/Assignment31_40/Assignment36_6.java
src/smitaVetal/Assignment31_40/Assignment36_7.java

prog1-
prog2 -
prog3-
prog4-
prog5-
prog6-
prog7-

Assignment36_Smita

---

src/apurvaBabel/Assignment31to40/Assignment38.java

Assignment38_ApurvaB

---

src/akankshaVyas/CollectionWork/Assignment37Collection.java

Assignment37 and restructure

---

src/gauravSahu/Assignment38A.java
src/gauravSahu/Assignment38B.java
src/gauravSahu/Assignment38C.java
src/gauravSahu/Assignment38D.java

Assignment_38_Gaurav

---

src/sagarY/Assignment_38/GetMiddleChar.java
src/sagarY/Assignment_38/GetStringStartsWithVowel1Digit1Ucase.java
src/sagarY/Assignment_38/IncreaseStudMarksBy10.java
src/sagarY/Assignment_38/ReplaceString.java

Program 1
Program 2
Program 3
Program 4

Assignment38_sagarY

---

src/manjiri/assignment38/IncreaseMarks.java
src/manjiri/assignment38/ListOfArrayNames.java
src/manjiri/assignment38/ListOfNames.java
src/manjiri/assignment38/MiddleCharacter.java
src/manjiri/assignment38/ReplaceAllOccuranceOfGivenString.java

ReplaceAllOccuranceOfGivenString.java
IncreaseMarks.java
MiddleCharacter.java
ListOfArrayNames.java

Assignment38-Manjiri

---

src/rashmiG/Collections/ArrayListMiddleCharacterFromNames.java
src/rashmiG/Collections/ArrayListReplaceAllOccurencesOfName.java
src/rashmiG/Collections/ArrayListStudentMarks.java
src/rashmiG/Collections/ArrayListVowelDigitUpperCase.java

Program 1:
Program 2:
Program 3:
Program 4:

Assignment38_RashmiG

---

src/shubhamG/Assignment31to40/Assignment39SetProg1.java
src/shubhamG/Assignment31to40/Assignment39SetProg2.java
src/shubhamG/Assignment31to40/Assignment39SetProg3.java
src/shubhamG/Assignment31to40/Assignment39SetProg4.java
src/shubhamG/Assignment31to40/Assignment39SetProg5.java
src/shubhamG/Assignment31to40/Assignment39SetProg6.java
src/shubhamG/Assignment31to40/Assignment39SetProg7.java

Assignment39_Shubham

---

src/priyankaD/assignments_31_40/Assignment_35.java

Assignment_35_priyanka

---

src/pujaSah/ArrayListAssignments/DuplicateNumberRemovalUsingTreeSet.java
src/pujaSah/ArrayListAssignments/FindDuplicateNames.java
src/pujaSah/ArrayListAssignments/FindUniqueNamesUsingHashSet.java
src/pujaSah/ArrayListAssignments/RemoveDuplicateNumbersUsingLinkedHashSet.java
src/pujaSah/ArrayListAssignments/RemoveDuplicateNumbersUsingList.java
src/pujaSah/ArrayListAssignments/RemoveDuplicateNumbersUsingSet.java
src/pujaSah/ArrayListAssignments/UniqueCharacterUsingLinkedHashSet.java

output1:
output2:
output3:
output4:
output5:
output6:
output7:

Please review assignment 39

---

src/adittyThakare/collections/Assignment38_Program1.java
src/adittyThakare/collections/Assignment38_Program2.java
src/adittyThakare/collections/Assignment38_Program3.java
src/adittyThakare/collections/Assignment38_Program4.java

Program 1:
Program 2:
Program 3:
Program 4:

Assignment38_Aditty

---

src/shubhamG/Assignment31to40/Assignment38CollectionPractice1.java
src/shubhamG/Assignment31to40/Assignment38CollectionPractice2.java
src/shubhamG/Assignment31to40/Assignment38CollectionPractice3.java
src/shubhamG/Assignment31to40/Assignment38CollectionPractice4.java

Assignment38_Shubham

---

src/deepakPatil/Assignment33ArrayExamples/Assignment33_1.java
src/deepakPatil/Assignment33ArrayExamples/Assignment33_2.java
src/deepakPatil/Assignment33ArrayExamples/Assignment33_3.java
src/deepakPatil/Assignment33ArrayExamples/Assignment33_4.java
src/deepakPatil/Assignment33ArrayExamples/Assignment33_5.java
src/deepakPatil/Assignment33ArrayExamples/Assignment33_6.java
src/deepakPatil/Assignment33ArrayExamples/Assignment33_7.java

Assignment33_DeepakP

---

src/anujaD/Assignment29.java

Assignment29_Anuja

---

src/swapnilMaheshwari/Collection/ArrayList/Assignment37/RemMulipleOccOfName.java
src/swapnilMaheshwari/Collection/ArrayList/Assignment37/RemoveMulOccOfAllName.java
src/swapnilMaheshwari/Collection/ArrayList/Assignment37/RemoveNameFromArrList.java

Program 1- 
Program 2 -
Program 3-

Assignment37 swapnil m

---

src/deepakPatil/Assignment35ExceptionHandling/Assignment35.java

Assignment35_DeepakP

---

src/asthaSrivastava/collections/Assignment37RemoveName.java
src/asthaSrivastava/collections/RemoveMutipleOccOfName.java
src/asthaSrivastava/collections/RemoveMutliOccurance.java

Assignment37_Astha

---

src/harshalRane/Assignments/assignment37/arraylist/Assignment37ArrayList.java

Assignment37_Harshal

---

src/gauravSahu/Assignement23.java
src/gauravSahu/Assignment21.java
src/gauravSahu/Assignment23B.java
src/gauravSahu/Assignment23C.java
src/gauravSahu/Assignment23D.java
src/gauravSahu/Assignment24.java
src/gauravSahu/Assignment25.java
src/gauravSahu/Assignment25B.java
src/gauravSahu/Assignment26.java
src/gauravSahu/Assignment37A.java
src/gauravSahu/Assignment37B.java
src/gauravSahu/String18Assign.java

Assignment_37_Gaurav

---

src/sohail/array/DuplicateInArray.java
src/sohail/stringprograms/SiftZeroToEndOfArray.java
src/sohail/stringprograms/VowelCountStringArray.java

Assignment_30_Sohail

---

src/anujaD/Assignment30.java

Assignment30_Anuja

---

src/nehaniG/Arraylist/Assignment38.java

Assignment38 nehanig

---

src/anujaD/Assignment30.java
src/anujaD/Assignment35.java

Assignment35 anuja

---

src/vibhaS/Assignment/Assignment38_1.java
src/vibhaS/Assignment/Assignment38_2.java
src/vibhaS/Assignment/Assignment38_3.java

Assignment38_vibha

---

src/swatiM/assignment/Assignment_37.java

Assignment37_Swati

---

src/komalShrivastava/Collections/RemoveElementsInArrayList.java

Assignment - 37 : 12th Oct'2022

Assignment37_Komal

---

src/harshalRane/Assignments/assignment38/arraylist/Assignment38ArrayList.java

Assignment38_Harshal

---

src/komalShrivastava/ReplaceElementInArrayList.java

Assignment - 38 : 14th Oct'2022

Assignment38_Komal

---

src/saroj/arrayListPrograms/Assignment38.java

Assignment38 Saroj

---

src/shivaniLikhia/Assignment37.java

Assignment37_ShivaniL

---

src/vinod/Assignment/Assignment31.java

Assignment31

---

src/apurvaBabel/Assignment31to40/Assignment39.java

Assignment39_ApurvaB

---

src/vinod/Assignment/Assignment32A.java
src/vinod/Assignment/Assignment32B.java
src/vinod/Assignment/Assignment32C.java

Assignment32

---

src/nilamP/CollectionExample1.java

assignment38_Nilam

---

src/shraddhaRekhate/Assignment23/MaximumLengthWord.java
src/shraddhaRekhate/Assignment23/NoDidgitUpper.java
src/shraddhaRekhate/Assignment23/WordHAvingAtleastOneDigit.java
src/shraddhaRekhate/Assignment23/WordHAvingMaxUpperCase.java
src/shraddhaRekhate/Assignment28/COuntOfEachVowelInGivenStringArraySwitchCase.java
src/shraddhaRekhate/Assignment28/CountOfEachVowelInGIvenString.java
src/shraddhaRekhate/Assignment28/CountOfVowelsSwitchCase.java
src/shraddhaRekhate/Assignment28/ReturnFirstVowelFromString.java
src/shraddhaRekhate/Assignment34/Anagram.java
src/shraddhaRekhate/Assignment34/Factorial.java
src/shraddhaRekhate/Assignment34/Fibonacci.java
src/shraddhaRekhate/Assignment35/SumOfAllDigits.java
src/shraddhaRekhate/Assignment35/SumOfAllNumException.java
src/shraddhaRekhate/Assignment36/AsciiOfAtoZ.java
src/shraddhaRekhate/Assignment36/AsciiOfGivenChar.java
src/shraddhaRekhate/Assignment36/CHarcHavingAciivalue91to96.java
src/shraddhaRekhate/Assignment36/CharHoldingGivenAsciiValue.java
src/shraddhaRekhate/Assignment36/NextChar.java
src/shraddhaRekhate/Assignment36/ReturnCountOfDigits.java
src/shraddhaRekhate/Assignment36/ReturnNextChar.java

Assignment23_28_34_35_36_ShraddhaR

---

src/swapnilMaheshwari/Collection/ArrayList/Assignment38/ListOfStringUsingArrayList.java
src/swapnilMaheshwari/Collection/ArrayList/Assignment38/MarksUpdate.java
src/swapnilMaheshwari/Collection/ArrayList/Assignment38/MiddleCharacterForArrayList.java
src/swapnilMaheshwari/Collection/ArrayList/Assignment38/ReplaceAllOccOfGivenName.java

Program 1 -
Program 2 -
Program 3-
Program 4-

Assignment38_SwapnilM

---

src/swatiM/assignment/collection/Assignment_39.java

Assignment39_Swati

---

src/hindaviIngle/Assignment32_reverseNum.java
src/hindaviIngle/Assignment33_uniqueNumFromArray.java
src/hindaviIngle/Collections/Assignment38.java
src/hindaviIngle/Collections/Assignment39_Program1.java
src/hindaviIngle/Collections/Assignment39_Program2.java
src/hindaviIngle/Collections/Assignment39_Program3.java
src/hindaviIngle/Collections/Assignment39_Program4.java
src/hindaviIngle/Collections/Assignment39_Program5.java
src/hindaviIngle/Collections/Assignment39_Program6.java
src/hindaviIngle/Collections/Assignment39_Program7.java
src/hindaviIngle/Collections/Assignment_37.java
src/hindaviIngle/Test3_MiddleCharOfMaxLength.java

Assignment 39 hindavi

---

src/hindaviIngle/Assignment32_reverseNum.java
src/hindaviIngle/Assignment33_uniqueNumFromArray.java
src/hindaviIngle/Collections/Assignment_37.java
src/hindaviIngle/Test3_MiddleCharOfMaxLength.java

Assignmnet 37 hindavi

---

src/hindaviIngle/Assignment32_reverseNum.java
src/hindaviIngle/Assignment33_uniqueNumFromArray.java
src/hindaviIngle/Collections/Assignment38.java
src/hindaviIngle/Collections/Assignment_37.java
src/hindaviIngle/Test3_MiddleCharOfMaxLength.java

Assignment 38 hindavi

---

src/nilamP/CollectionExample2.java

assignment39_Nilam

---

src/apurvaBabel/Assignment31to40/Assignment40.java

Assignment40_ApurvaB

---

src/rashmiG/Collections/ArrayListRemoveDuplicatesFromArray.java
src/rashmiG/Collections/SetDuplicateNamesFromArray.java
src/rashmiG/Collections/SetRemoveDuplicatesFromNumbArrayINaturalOrder.java
src/rashmiG/Collections/SetRemoveDuplicatesFromNumbArrayInsertionOrder.java
src/rashmiG/Collections/SetRemoveNumberDuplicatesFromArray.java
src/rashmiG/Collections/SetUniqueCharactersFromName.java
src/rashmiG/Collections/SetUniqueNamesFromArray.java

Program 1:
Program 2:
Program 3:
Program 4:
Program 5:
Program 6:
Program 7:

Assignment39_RashmiG

---

src/pranjaliV/assignment37/CollectionAssignment37.java

Assignment_37_Pranjali

---

src/adittyThakare/collections/Assignment39_Program1.java
src/adittyThakare/collections/Assignment39_Program2.java
src/adittyThakare/collections/Assignment39_Program3.java
src/adittyThakare/collections/Assignment39_Program4.java
src/adittyThakare/collections/Assignment39_Program5.java
src/adittyThakare/collections/Assignment39_Program6.java
src/adittyThakare/collections/Assignment39_Program7.java

Program 1:
Program 2:
Program 3:
Program 4:
Program 5:
Program 6:
Program 7:

Assignment39_Aditty

---

src/nikeshM/Assignment33/Assignment33DuplicateName.java
src/nikeshM/Assignment33/Assignment33DuplicateNo.java
src/nikeshM/Assignment33/Assignment33MissingNo.java
src/nikeshM/Assignment33/Assignment33UniqueName.java
src/nikeshM/Assignment33/Assignment33UniqueNo.java
src/nikeshM/Assignment33/AssignmentNo33FrequencyOfGivenNo.java

Assignment_33_Nikesh

---

src/vibhaS/Assignment/Assignment39.java

Assignment39_vibha

---

src/sagarY/Assignment_39/PrintDuplicateNamesUsingSet.java
src/sagarY/Assignment_39/PrintDuplicateNumbersInNaturalOrder.java
src/sagarY/Assignment_39/PrintDuplicateNumbersUsingHashSet.java
src/sagarY/Assignment_39/PrintDuplicateNumbersUsingList.java
src/sagarY/Assignment_39/PrintDuplicateNumbersUsingSet.java
src/sagarY/Assignment_39/PrintUniqueCharUsingSet2.java
src/sagarY/Assignment_39/PrintUniqueNamesUsingSet.java

Assignment39_sagarY

---

src/asthaSrivastava/collections/AddMarksBy10.java
src/asthaSrivastava/collections/ReplaceName.java
src/asthaSrivastava/collections/ReturnMiddleChar.java
src/asthaSrivastava/collections/ReturnNameWithVowelsDigitUpperCase.java

Program1
Program 2
Program 3
Program 4

Assignment38_Astha

---

src/sanket/ArrayListAssignment38.java
src/sanket/HashSetAssignment39.java

Assignment39_Sanket

---

src/sanket/ArrayListAssignment38.java

Assignment38_Sanket

---

src/deepakPatil/Assignment38ArrayList/Assignment38_1.java
src/deepakPatil/Assignment38ArrayList/Assignment38_2.java
src/deepakPatil/Assignment38ArrayList/Assignment38_3.java
src/deepakPatil/Assignment38ArrayList/Assignment38_4.java

Assignment38_DeepakP

---

src/komalShrivastava/HashSetGames.java

Assignment39_Komal

---

src/saroj/collectionsProgram/Assignment39.java

Assignment39 Saroj

---

src/nehaniG/Arraylist/Assignment39.java

Assignment39_Nehanig

---

src/deepakPatil/Assignment39Set/Assignment39_1.java
src/deepakPatil/Assignment39Set/Assignment39_2.java
src/deepakPatil/Assignment39Set/Assignment39_3.java
src/deepakPatil/Assignment39Set/Assignment39_4.java
src/deepakPatil/Assignment39Set/Assignment39_5.java
src/deepakPatil/Assignment39Set/Assignment39_6.java

Assignment39_DeepakP

---

src/komalShrivastava/ArrayListMapPrograms.java

Assignment40_Komal

---

src/pranjaliV/assignment35/ExceptionHandlingEx35.java

Assignment_35_Pranjali

---

src/nehaniG/Arraylist/Assignment40.java

Assignment40_Nehanig

---

src/harshalRane/Assignments/assignment40/FindFreqOfNum.java
src/harshalRane/Assignments/assignment40/FindFreqUsingMap.java
src/harshalRane/Assignments/assignment40/FreqOfEachNumUsingMap.java
src/harshalRane/Assignments/assignment40/FreqOfEachWordUsingMap.java
src/harshalRane/Assignments/assignment40/MissingNumbersFromArray.java
src/harshalRane/Assignments/assignment40/ReverseStringBuilder.java
src/harshalRane/Assignments/assignment40/ReverseStringInplaceReverse.java

Program 1:
Program 2:
Program 3:
Program 4:
Program 5:
Program 6:
Program 7:

Assingment40_Harshal

---

src/manjiri/assignment40/FrequencyOfCharacter.java
src/manjiri/assignment40/FrequencyOfNumberUsingArrayList.java
src/manjiri/assignment40/FrequencyOfNumbers.java
src/manjiri/assignment40/FrequencyOfWords.java
src/manjiri/assignment40/MissingNumbers.java
src/manjiri/assignment40/ReverseStringInplaceReplace.java
src/manjiri/assignment40/ReverseStringUsingStringBuilder.java

FrequencyOfNumberUsingArrayList.java
MissingNumbers.java
ReverseStringInplaceReplace.java
ReverseStringUsingStringBuilder.java
FrequencyOfCharacter.java
FrequencyOfWords.java
FrequencyOfNumbers.java

Assignment40-Manjiri

---

src/pranjaliV/assignment38/CollectionEx38.java

Assignment_38_Pranjali

---

src/swapnilMaheshwari/Collection/SetPrograms/Assignment39/DuplicatNameUsingSet.java
src/swapnilMaheshwari/Collection/SetPrograms/Assignment39/DuplicatNumSet.java
src/swapnilMaheshwari/Collection/SetPrograms/Assignment39/IdentifyDuplicateUsingList.java
src/swapnilMaheshwari/Collection/SetPrograms/Assignment39/IdntifyDuplicatesUsingSet.java
src/swapnilMaheshwari/Collection/SetPrograms/Assignment39/RemDupliUsingTreeHashSet.java
src/swapnilMaheshwari/Collection/SetPrograms/Assignment39/UniqueCharacters.java
src/swapnilMaheshwari/Collection/SetPrograms/Assignment39/UniqueNameHashSet.java

Program 1-
Program 2-
Program 3-
Program 4-
Program 5-
Program 6-
Program 7-

Assingment39_SwapnilM

---

src/namratamishra_assignment_33_Array_Operations/ArrayNumberPrintWithFrequency.java
src/namratamishra_assignment_33_Array_Operations/ArrayPrintDuplicateNumber.java
src/namratamishra_assignment_33_Array_Operations/ArrayPrintMissingNumber1to10InArray.java
src/namratamishra_assignment_33_Array_Operations/ArrayPrintUniqueNames.java
src/namratamishra_assignment_33_Array_Operations/ArrayPrintUniqueNumber.java
src/namratamishra_assignment_33_Array_Operations/ArrayPrintUniqueNumberHavingFreq1.java
src/namratamishra_assignment_33_Array_Operations/ArrayStringDuplicateWordsPrint.java

namrata_mishra_assignment_33

---

src/gauravSahu/Assignment40A.java
src/gauravSahu/Assignment40B.java
src/gauravSahu/Assignment40C.java
src/gauravSahu/Assignment40D.java
src/gauravSahu/Assignment40E.java
src/gauravSahu/Assignment40F.java
src/gauravSahu/Assignment40G.java

Assignment_40_Gaurav

---

src/gauravSahu/Assignment39A.java
src/gauravSahu/Assignment39B.java
src/gauravSahu/Assignment39C.java
src/gauravSahu/Assignment39D.java
src/gauravSahu/Assignment39E.java
src/gauravSahu/Assignment39F.java
src/gauravSahu/Assignment39G.java

Assignment_39_Gauarv

---

src/nikitaPhase/Assignment_24.java

Assignment_24_TejasP

---

src/nikitaPhase/Assignment_23_1.java
src/nikitaPhase/Assignment_23_2.java
src/nikitaPhase/Assignment_23_3.java
src/nikitaPhase/Assignment_23_4.java

Assignment_23_1to4_TejasP

---

src/nikitaPhase/Assignment_22.java

Assignment22_TejasP

---

src/ankitaBarwad/ExceptionHandling.java

Assignment35_AnkitaB

---

src/pujaSah/MapAssignments/CharFrequencyCalculationUsingMap.java
src/pujaSah/MapAssignments/FindMissingNumber.java
src/pujaSah/MapAssignments/NumberFrequencyUsingArrayList.java
src/pujaSah/MapAssignments/NumberFrequencyUsingMap.java
src/pujaSah/MapAssignments/ReverseString.java
src/pujaSah/MapAssignments/StringReverse.java
src/pujaSah/MapAssignments/WordFrequencyUsingMap.java

output1:
output2:
output3:
output4:
output5:
output6:
output 7:

Please review assignment 40

---

src/asthaSrivastava/array/assignments/collections/FindMissingNum.java
src/asthaSrivastava/array/assignments/collections/FreqOfCharUsingMap.java
src/asthaSrivastava/array/assignments/collections/FrequencyOfNumUsingArrayList.java
src/asthaSrivastava/array/assignments/collections/NumFreqUsingMap.java
src/asthaSrivastava/array/assignments/collections/ReturnStringUsingInplaceRev.java
src/asthaSrivastava/array/assignments/collections/ReverseStringUsingSB.java
src/asthaSrivastava/array/assignments/collections/StringFreqUsingMap.java

Program 1
Program 2
Program 3
Program 4
Program 5
Program 6
Program 7

Assignment40_Astha

---

src/nikeshM/Assignment35/Assignment35ExceptionProgram1.java
src/nikeshM/Assignment35/Assignment35Program2.java

 Assignment_35_Nikesh

---

src/nikeshM/Assignment34/Assignment34Anagram.java
src/nikeshM/Assignment34/Assignment34Factorial.java
src/nikeshM/Assignment34/Assignment34Fibonacci.java

Assignment_34_Nikesh

---

src/harshalRane/Assignments/assignment39/DuplicateNamesArray.java
src/harshalRane/Assignments/assignment39/RemoveDuplicateAscOrder.java
src/harshalRane/Assignments/assignment39/RemoveDuplicateNum.java
src/harshalRane/Assignments/assignment39/RemoveDuplicateNumUsingList.java
src/harshalRane/Assignments/assignment39/RemoveDuplicateUsingSet.java
src/harshalRane/Assignments/assignment39/UniqueCharactersFromName.java
src/harshalRane/Assignments/assignment39/UniqueNamesFromArrayUsingHashSet.java

Assignment39_Harshal

---

src/shrutiArora/Assignment33.java
src/shrutiArora/Assignment34.java
src/shrutiArora/Assignment35.java
src/shrutiArora/Assignment36.java

Assignment33_36_shruti

---

src/pranjaliV/assignment40/CollectionEx40.java

Assignment_40_Pranjali

---

src/pujaSah/CollectionsAssignment/Employee.java
src/pujaSah/assignments20_30/ArrayAndString.java

Please review Assignment 41

---

src/rashmiG/Collections/ArrayListFrequencyOfNumberUsingArrayAndWhileloop.java
src/rashmiG/Collections/ArrayListMissingNumbers.java
src/rashmiG/Collections/MapFrequencyOfEachCharacter.java
src/rashmiG/Collections/MapFrequencyOfEachWordInString.java
src/rashmiG/Collections/MapNumberFrequencyInArray.java
src/rashmiG/ReverseStringDifferentApproaches/ReverseStringUsingInplaceReverse.java
src/rashmiG/ReverseStringDifferentApproaches/ReverseStringUsingStringBuider.java

Program 1:
Program 2:
Program 3:
Program 4:
Program 5:
Program 6:
Program 7:

Assignment40_RashmiG

---

src/ankitaBarwad/ArrayList_Assignment37.java

Assignment37_AnkitaB

---

src/swapnilMaheshwari/collection/MAPprograms/FreqOfEachCharUsingMap.java
src/swapnilMaheshwari/collection/MAPprograms/FreqOfEachNumberUsingArrayList.java
src/swapnilMaheshwari/collection/MAPprograms/FreqOfEachNumberUsingMap.java
src/swapnilMaheshwari/collection/MAPprograms/FreqOfEachWordInStringUsingMap.java
src/swapnilMaheshwari/collection/MAPprograms/MissingNumberInList.java
src/swapnilMaheshwari/collection/MAPprograms/ReverseString.java
src/swapnilMaheshwari/collection/MAPprograms/ReverseStringUsingStringBuffer.java

Program 1-
Program 2-
Program 3-
Program 4-
Program 5-
Program 6-
Program 7-

Assignment40_SwapnilM

---

src/vibhaS/Assignment/Assignment40.java

Assignment40_vibha

---

src/sagarY/Assignment40_CollectionHashMap/FindMissingNumbers.java
src/sagarY/Assignment40_CollectionHashMap/PrintFreqOfEachCharUsingMap.java
src/sagarY/Assignment40_CollectionHashMap/PrintFreqOfEachNum.java
src/sagarY/Assignment40_CollectionHashMap/PrintFreqOfEachNumUsingMap.java
src/sagarY/Assignment40_CollectionHashMap/PrintFreqOfEachStringUsingMap.java
src/sagarY/Assignment40_CollectionHashMap/ReverseStringUsingInplace.java
src/sagarY/Assignment40_CollectionHashMap/ReverseStringUsingStringBuffer.java

Program 1
Program 2:
Program 3:
Program 4:
Program 5:
Program 6:
Program 7:

Assignment40_sagarY

---

src/adittyThakare/collections/Assignment40_Program1.java
src/adittyThakare/collections/Assignment40_Program2.java
src/adittyThakare/collections/Assignment40_Program3.java
src/adittyThakare/collections/Assignment40_Program4.java
src/adittyThakare/collections/Assignment40_Program5.java
src/adittyThakare/collections/Assignment40_Program6.java
src/adittyThakare/collections/Assignment40_Program7.java

Program1:
Program2:
Program3:
Program 4:
Program5:
Program6:
Program7:

Assignment40_Aditty

---

src/asthaSrivastava/collections/assignment41/EmpComparable.java
src/asthaSrivastava/collections/assignment41/Employee.java

Assignment41 astha

---

src/swapnilMaheshwari/Collection/Comparator/Assignment42/EmpIdComparator.java
src/swapnilMaheshwari/Collection/Comparator/Assignment42/EmpNameComparator.java
src/swapnilMaheshwari/Collection/Comparator/Assignment42/EmpSalaryComparator.java
src/swapnilMaheshwari/Collection/Comparator/Assignment42/EmployeeData.java
src/swapnilMaheshwari/Collection/Comparator/Assignment42/EmployeeDetails.java

Assignment42_SwapnilM

---

src/komalShrivastava/Collections/Comparator/ComparatorSortTestClass.java
src/komalShrivastava/Collections/Comparator/Employee.java
src/komalShrivastava/Collections/Comparator/EmployeeEmpDeptIDComparator.java
src/komalShrivastava/Collections/Comparator/EmployeeEmpIDComparator.java
src/komalShrivastava/Collections/Comparator/EmployeeEmpNameComparator.java
src/komalShrivastava/Collections/Comparator/EmployeeSalaryComparator.java

Assignment - 42 : 21th Oct'2022
Sort Employee object based multiple attribute like name , id, Salary.
Employee class should have empName, empId, empSalary, empDeptId as parameters.
Print all instance variable of employee after sorting.
Hint : Use Comparator.

Assignment42_Komal

---

src/rashmiG/Collections/Assignment42_Comparator/Employee.java
src/rashmiG/Collections/Assignment42_Comparator/EmployeeDeptId.java
src/rashmiG/Collections/Assignment42_Comparator/EmployeeId.java
src/rashmiG/Collections/Assignment42_Comparator/EmployeeJoiningDate.java
src/rashmiG/Collections/Assignment42_Comparator/EmployeeName.java
src/rashmiG/Collections/Assignment42_Comparator/EmployeeSalary.java
src/rashmiG/Collections/Assignment42_Comparator/Test.java

Assignment42_RashmiG

---

src/komalShrivastava/Collections/ArrayListMapPrograms.java
src/komalShrivastava/Collections/ComparableSortTestClass.java
src/komalShrivastava/Collections/Employee.java
src/komalShrivastava/Collections/HashSetGames.java
src/komalShrivastava/Collections/ReplaceElementInArrayList.java

Assignment - 41 : 20th Oct'2022
Sort Employee object based on Salary.
Employee class should have empName, empId, empSalary, empDeptId as parameters.
Print all instance variable of employee after sorting.

Assignment41_Komal and moved files to collections folder

---

src/manjiri/assignment42/Employee.java
src/manjiri/assignment42/EmployeeDeptIdComparator.java
src/manjiri/assignment42/EmployeeIdComparator.java
src/manjiri/assignment42/EmployeeJoiningDateComparator.java
src/manjiri/assignment42/EmployeeNameComparator.java
src/manjiri/assignment42/EmployeeSalaryComparator.java
src/manjiri/assignment42/Test.java

Assignment42-Manjiri

---

src/sagarY/collection/assignment_41/EmployeeDetails.java
src/sagarY/collection/assignment_41/Manager.java
src/sagarY/collection/assignment_42/EmployeeDetails.java
src/sagarY/collection/assignment_42/EmployeeIdComparator.java
src/sagarY/collection/assignment_42/EmployeeJoinigDateComparator.java
src/sagarY/collection/assignment_42/EmployeeNameComparator.java
src/sagarY/collection/assignment_42/EmployeeSalaryComparator.java
src/sagarY/collection/assignment_42/Manager.java

Assignment 41 - Employee Sort by "Comparable"
Assignment 42 - Employee Sort by "Comparator"

Assignment41_42_sagarY

---

src/hemanshi/Assignment_37.java

Assignment_37

---

src/harshalRane/Assignments/assignment42/comparator/Admin.java
src/harshalRane/Assignments/assignment42/comparator/Employee.java
src/harshalRane/Assignments/assignment42/comparator/EmployeeIDComparator.java
src/harshalRane/Assignments/assignment42/comparator/EmployeeNameComparator.java
src/harshalRane/Assignments/assignment42/comparator/EmployeeSalaryComparator.java

Assignment 42 - Sorting on empID
Assignment 42 - Sorting on empName
Assignment 42 - Sorting on empSalary

Assignment42_Harshal

---

src/pujaSah/CollectionsAssignment/DateOfJoiningComparator.java
src/pujaSah/CollectionsAssignment/EmpIdComparator.java
src/pujaSah/CollectionsAssignment/EmployeeDetails.java
src/pujaSah/CollectionsAssignment/EmployeeManagement.java
src/pujaSah/CollectionsAssignment/NameComparator.java
src/pujaSah/CollectionsAssignment/SalaryComparator.java

DateOfJoining Comparator output:
Employee POJO class:
DOJ comparator class:
Name comparator class:
Empid comparator class:
salary comparator class:

Please review Assignment42

---

src/sanket/collectionscomparable/Client.java
src/sanket/collectionscomparable/Employee.java

Assignment41_Sanket

---

src/harshalRane/Assignments/assignment41Comparable/Employee.java
src/harshalRane/Assignments/assignment41Comparable/EmployeeDetailsComparable.java

Assignment41_Harshal

---

src/asthaSrivastava/array/assignments/collections39/A39_PrintDuplicateNames.java
src/asthaSrivastava/array/assignments/collections39/A39_UniqueName.java
src/asthaSrivastava/array/assignments/collections39/RemDuplicateUsingList.java
src/asthaSrivastava/array/assignments/collections39/RemDuplicateUsingSet.java
src/asthaSrivastava/array/assignments/collections39/RemoveDuplicates1.java
src/asthaSrivastava/array/assignments/collections39/RemoveDuplicatesAsc.java
src/asthaSrivastava/array/assignments/collections39/ReturnUniqueChar.java

Program1
Program 2
Program 3
Program 4
Program 5
Program 6
Program 7

Assignment39_Astha

---

src/rashmiG/Collections/Assignment41_POJOclass_empDetails/Employee.java
src/rashmiG/Collections/Assignment41_POJOclass_empDetails/Test.java

Assignment41_RashmiG

---

src/manjiri/assignment41/Employee.java
src/manjiri/assignment41/Test.java

Assignment41-Manjiri

---

src/saroj/arrayListPrograms/Assignment40.java

Assignment40 Saroj

---

src/ankitaBarwad/Assignment38_ListMethods.java

Assignment38_AnkitaB

---

src/vinod/Assignment/Assignment33A.java
src/vinod/Assignment/Assignment33B.java
src/vinod/Assignment/Assignment33C.java
src/vinod/Assignment/Assignment33D.java

Assignment33

---

src/apurvaBabel/Assignment41to50/Assignment41_SortingOfEmployees.java
src/apurvaBabel/Assignment41to50/Employee.java

Assignment41_ApurvaB

---

src/pranjaliV/assignment42/Assignment42.java
src/pranjaliV/assignment42/Employee.java
src/pranjaliV/assignment42/EmployeeIdComparator.java
src/pranjaliV/assignment42/EmployeeNameComparator.java
src/pranjaliV/assignment42/EmployeeSalaryComparator.java

Assignment_42_Pranjali

---

src/hindaviIngle/Collections/Assignment40_Program1.java
src/hindaviIngle/Collections/Assignment40_Program2.java
src/hindaviIngle/Collections/Assignment40_Program3.java
src/hindaviIngle/Collections/Assignment40_Program4.java
src/hindaviIngle/Collections/Assignment40_Program5.java
src/hindaviIngle/Collections/Assignment40_Program6.java
src/hindaviIngle/Collections/Assignment40_Program7.java

Assignment_40_Hindavi

---

src/hindaviIngle/Collections/Assignment40_Program1.java
src/hindaviIngle/Collections/Assignment40_Program2.java
src/hindaviIngle/Collections/Assignment40_Program3.java
src/hindaviIngle/Collections/Assignment40_Program4.java
src/hindaviIngle/Collections/Assignment40_Program5.java
src/hindaviIngle/Collections/Assignment40_Program6.java
src/hindaviIngle/Collections/Assignment40_Program7.java
src/hindaviIngle/Collections/Assignment41_Client.java
src/hindaviIngle/Collections/Assignment_41_Employee.java

Assignment 41 hindavi

---

src/hindaviIngle/Collections/Assignment40_Program1.java
src/hindaviIngle/Collections/Assignment40_Program2.java
src/hindaviIngle/Collections/Assignment40_Program3.java
src/hindaviIngle/Collections/Assignment40_Program4.java
src/hindaviIngle/Collections/Assignment40_Program5.java
src/hindaviIngle/Collections/Assignment40_Program6.java
src/hindaviIngle/Collections/Assignment40_Program7.java
src/hindaviIngle/Collections/Assignment41_Client.java
src/hindaviIngle/Collections/Assignment_41_Employee.java
src/hindaviIngle/Comparator/Employee.java
src/hindaviIngle/Comparator/EmployeeEmpDeptIDComparator.java
src/hindaviIngle/Comparator/EmployeeEmpIDComparator.java
src/hindaviIngle/Comparator/EmployeeEmpNameComparator.java
src/hindaviIngle/Comparator/EmployeeSalaryComparator.java
src/hindaviIngle/Comparator/SortEmployeeDetails.java

Assignment 42 hindavi

---

src/nilamP/assignment41/Employee.java
src/nilamP/assignment41/EmployeeDetails.java

assignment41_Nilam

---

src/adittyThakare/comparator/EmployeeDeptIdComparator.java
src/adittyThakare/comparator/EmployeeIdComparator.java
src/adittyThakare/comparator/EmployeeNameComparator.java
src/adittyThakare/comparator/EmployeeNew.java
src/adittyThakare/comparator/EmployeeSalaryComparator.java
src/adittyThakare/comparator/TestComparator.java

Assignment42_Aditty

---

src/akankshaVyas/CollectionWork/Assignment40.java

Assignment40

---

src/akankshaVyas/CollectionWork/Employee.java

Assignment41

---

src/akankshaVyas/CollectionWork/Employee1.java
src/akankshaVyas/CollectionWork/Employee1Admin.java
src/akankshaVyas/CollectionWork/EmployeeDeptIDComparator.java
src/akankshaVyas/CollectionWork/EmployeeIDComparator.java
src/akankshaVyas/CollectionWork/EmployeeNameComparator.java
src/akankshaVyas/CollectionWork/EmployeeSalaryComparator.java

Assignment42

---

src/sanket/collectioncomparator/Client.java
src/sanket/collectioncomparator/Employee.java
src/sanket/collectioncomparator/SortEmployeeDepartID.java
src/sanket/collectioncomparator/SortEmployeeID.java
src/sanket/collectioncomparator/SortEmployeeName.java
src/sanket/collectioncomparator/SortEmployeeSalary.java

Assignment 42 : Result
Sort Employee object based multiple attribute like name , id, Salary.
Employee class should have empName, empId, empSalary, empDeptId as parameters.
Print all instance variable of employee after sorting.
Hint : Use Comparator.

Assignment42_Sanket

---

src/vibhaS/Assignment41To50/Assignment41_SortingOfEmployee.java
src/vibhaS/Assignment41To50/Employee.java

Employee Details-->empId, empName, empSalary, empDepId:-
6 --> Usha --> 3000 -->1004
1 -->Vibha -->5000 -->1001
8 --> Mahesh -->5000 -->1005
3 --> Krishna -->6000 --> 1003
7 --> Sachin -->7000 -->1000
4 --> Yashwant --> 9000 --> 1002

Assignmenmt41_vibha

---

src/hemanshi/Assignment_38.java

Assignment_38

---

src/pranjaliV/assignment39/CollectionEx39.java

Assignment_39_Pranjali

---

src/rohanNaik/Assignments/Assignment35Exception.java
src/rohanNaik/Assignments/Assignment35b.java

Rohan_Assignment_35

---

src/nehaniG/Arraylist/Assignment41_EmployeeSorting.java
src/nehaniG/Arraylist/Employee.java

Assignment41 nehanig

---

src/vibhaS/Assignment42/Assignment42.java
src/vibhaS/Assignment42/Employee1.java
src/vibhaS/Assignment42/EmployeeNameDetails.java
src/vibhaS/Assignment42/EmployeeSalaryDetails.java

Assignment42_vibha

---

src/rohanNaik/Assignments/Assignment38.java

Rohan_Assignment-38

---

src/swatiM/assignment/collection/Assignment41_Employee.java
src/swatiM/assignment/collection/Assignment41_EmployeeDetailsComparable.java

Assignment41_Swati

---

src/asthaSrivastava/assignment42/EmpDetaisCompare.java
src/asthaSrivastava/assignment42/Employee.java
src/asthaSrivastava/assignment42/EmployeeDeptIdCompare.java
src/asthaSrivastava/assignment42/EmployeeIdCompare.java
src/asthaSrivastava/assignment42/EmployeeNameCompare.java
src/asthaSrivastava/assignment42/EmployeeSalaryCompare.java

Assignment42_Astha

---

src/shraddhaRekhate/Assignment38/Assignment38.java

Assignment38_ShraddhaR

---

src/pranjaliV/assignment_41/Assignment_41.java
src/pranjaliV/assignment_41/Employee.java

Assignment_41_Pranjali

---

src/shrutiArora/Assignment37.java
src/shrutiArora/Assignment38.java
src/shrutiArora/Assignment39.java
src/shrutiArora/Assignment40.java

Assignment37_40_shruti

---

src/deepakPatil/Assignment34AnagramFactorialFibonacci/Assignment34_StringAnagram.java
src/deepakPatil/Assignment34AnagramFactorialFibonacci/FactorialCode.java
src/deepakPatil/Assignment34AnagramFactorialFibonacci/FibonacciSeries.java

Assignment34_DeepakP
